module.exports = {
  screen: '',
  time: 0,

  //  BASE_URL: 'http://134.209.159.180/kundali_expert/api/',
  BASE_URL: 'http://139.59.94.54/kundali_expert/api/',
  firebaseToken: '',
  APPID: 'ca009ba1067043a7b3dff61bb2c297df',
  lan: 'en',
  helpline_number: '',
  ASTRO_API_BASE_URL:
    'http://139.59.94.54/kundali_expert/astrology_api/global_api',

  ASTRO_APIS_URL: 'https://json.astrologyapi.com/v1/',
  ASTRO_APIS_PACKAGE: 'Premium ',
  ASTRO_APIS_USERID: '609418',
  ASTRO_APIS_API_KEY: '3f44385e5c9a4a5febc2e9ea7872bacf',

  YOUTUBE_API: 'AIzaSyA7jAUh4B0Rk5YUsQ7QlUzL4Wd0GoV50ME',
  response: '',
  myname: '',
  magid: '',
  ctype: '',
  mode: '',
  prices: '',
  times: '',
  tre: '',
  rescd: '',
  resct: '',
  token: '',

  loginmobile: '',
  loginOTP: '',
  loginCtryCode: '',

  opentok_api_key: '46593922',

  totalAmount: '',
  isSavedKundli: '0',
  astrodetail: {},
  savedKundliDetails: {},
  glLanguage: 'en',
  glChartStyle: 'north',
  gldate: '',
  locationid: '',
  vid: '',
  pid: '',
  morning: '',
  evening: '',
  venueid: '',
  glmonth: '',
  glyear: '',
  glhour: '',
  glminute: '',
  gllat: 17.2323232,
  gllong: 83.232332,
  glzone: '5.5',
  glgender: 'male',

  followup_code: '',
  followup_user_type: '',
  //    globalTax:0,
  gemsTax: 0.0,
  classTax: 0.0,
  in_personTax: 0.0,
  online_consultTax: 0.0,
  life_predTax: 0.0,
  match_makingTax: 0.0,
  medical_bookTax: 0.0,
  financial_bookTax: 0.0,
  pdf_bookTax: 0.0,
  varsh_bookTax: 0.0,
  magzine_bookTax: 0.0,
  rashisphal_bookTax: 0.0,
  data: {},

  home: 'home',
  Signin: 'Signin',
  guid: '',
  edit_profLat: '',
  edit_profLong: '',
  edit_profAddress: '',
  another: '70',
  user_id: '72',
  walletAmount: 0,
  bookingid: '333',
  headerTitle: '',
  consultType: '',
  deviceIp: '',
  deviceManuf: '',
  deviceCarrier: '',

  event_details: {},

  videoDetails: '',
  prodDetails: '',
  catDetails: '',
  all_settings: '',
  userDetails: {},
  addressId: '',

  expId: '',
  expbio: '',
  name: '',

  signupName: '',
  signupEmail: '',
  signupMobile: '',
  signupCountryCode: '',
  signupDob: '',
  signupTob: '',
  signupPob: '',
  signupGender: '',
  signupReferCode: '',
  signupOtp: '',
  signupVerifyRefer: '',
  signupApplyRefer: '',
  signupCtryCode: '',
};
