import LocalizedStrings from 'react-native-localization';
let stringsoflanguagess = new LocalizedStrings({
  hi: {
    puja: 'पूजा',
    reschedule: 'पुनर्निर्धारित',
    cancel: 'रद्द करना',
    amountpaid: 'राशि का भुगतान',
    book: 'बुक करे',
    prefer: 'संपर्क का पसंदीदा तरीका',
    pplease1:
      'आप जिस व्यक्ति के लिए अपॉइंटमेंट ले रहे हैं, उसके बारे में कृपया निम्नलिखित जानकारी प्रदान करें।',
    proceed: 'आगे बढ़ना',
    changeslot: 'क्या आप स्लॉट बदलना चाहते हैं?',
    bookan: 'एक ज्योतिषी बुक करें',
    consultan: 'तीन आसान चरणों का उपयोग करके किसी ज्योतिषी से परामर्श करें',
    signupwith: 'एस्ट्रोज्योतिष के साथ साइन अप करें',
    bookan: 'एक अपॉइंटमेंट बुक करें',
    getacallback: 'कॉल बैक प्राप्त करें',
    explore: 'एक्सप्लोर करें और हमारे ज्योतिषियों के साथ अपॉइंटमेंट बुक करें',
    confirm: 'पुष्टीकरण',
    bookigsucessful: 'ऑनलाइन पूजा के लिए बुकिंग सफल',
    bookigsucessful1: 'बुकिंग सफल',
    referenceid: 'आपकी बुकिंग संदर्भ आईडी',
    youwillget: 'आपको एस्ट्रोज्योतिष टीम से एक पुष्टिकरण मेल प्राप्त होगा',
    yes: 'हां',
    iconfirm:
      'मैं पुष्टि करता हूं कि मैंने उपरोक्त डेटा सत्यापित किया है और यह सटीक है।',
    iam18: 'मेरी आयु 18 और उससे अधिक है',
    ihaveunderstood: 'मैंने पढ़ और समझ लिया है',
    onlinepujabookig: 'ऑनलाइन पूजा बुकिंग',
    pplease:
      'कृपया उस व्यक्ति के बारे में निम्नलिखित जानकारी प्रदान करें जिसे आप ऑनलाइन पूजा के लिए बुक कर रहे हैं।',
    book: 'बुक',
    select: 'चुनते हैं',
    purohit: 'पुरोहित',
    thankyou: 'धन्यवाद !',
    busy: 'ज्योतिषी वर्तमान में व्यस्त है। कृपया किसी अन्य ज्योतिषी को चुनें या कुछ समय के लिए प्रतीक्षा करें और कॉन्सुलेशन फिर से शुरू करें',
    offline:
      'ज्योतिषी वर्तमान में ऑफलाइन है। कृपया किसी अन्य ज्योतिषी को चुनें या कुछ समय के लिए प्रतीक्षा करें और कॉन्सुलेशन फिर से शुरू करें',
    ok: 'ठीक है',
    refer: 'रेफरल के बाद आपके दोस्त को ₹30 मिलते हैं',
    enter: 'अपना रेफरल कोड दर्ज करें',
    ask: 'रेफरल कोड के लिए अपने परिवार या दोस्तों से पूछें',
    submit: 'प्रस्तुत',
    contactus: 'संपर्क करें',
    emailus: 'हमे ईमेल करे',
    whatsappchat: 'व्हाट्सएप चैट',
    callus: 'हमें 24/7 कॉल करें हम आपको जवाब देंगे',
    getsolution: 'समाधान को अपने इनबॉक्स में प्रसारित करें',
    startaconverstion: 'व्हाट्सएप के साथ अभी बातचीत शुरू करें',
    formore: 'अधिक जानकारी के लिए, पर एक ईमेल ड्रॉप करें',
    faq: 'अक्सर पूछे जाने वाले प्रश्न',
    howsignup: 'मैं कैसे साइन अप कर सकता हूँ?',
    step1: 'स्टेप 1- ऐप खोलें और साइन अप पर क्लिक करें।',
    step2:
      'चरण 2- वह मोबाइल नंबर दर्ज करें जिसे आप एस्ट्रोज्योतिष पर पंजीकृत करना चाहते हैं।',
    step3:
      'चरण 3- साइन अप पर क्लिक करें और ओटीपी दर्ज करें जो आपको मोबाइल नंबर पर एसएमएस के माध्यम से प्राप्त होगा।',
    step4:
      'एक बार जब आप सफलतापूर्वक साइन अप कर लेते हैं, तो आप आवश्यक विवरण भर सकते हैं और भारत के सर्वश्रेष्ठ ज्योतिषियों से परामर्श करना शुरू कर सकते हैं',
    contactus: 'संपर्क करें',
    howitwork: 'यह कैसे कार्य करता है ?',
    support: 'सहायता',
    inviteviasms: 'एसएमएस द्वारा आमंत्रित करें',
    callus1: 'हमें कॉल करें',
    follow: 'पालन ​​करना',
    followed: 'पीछा किया',
    invite: 'आमंत्रित करें और कमाएँ',
    freebalance: 'मुक्त संतुलन',
    after: 'साइन-अप और फोन सत्यापन के बाद।',
    isstep31: 'जब आपका दोस्त रिचार्ज करता है।',
    sharelink:
      'लिंक को अपने मित्रों और परिवार के साथ साझा करें, आप दोनों को पुरस्कृत किया जाएगा।',
    yourrefer: 'आपका रेफरल कोड है',
    invitevia: 'या के माध्यम से आमंत्रित करें',
    refer3: '3 आसान चरणों में देखें और कमाएं',
    istep1: 'चरण 1 - किसी मित्र को आमंत्रित करें।',
    istep2:
      'स्टेप 2- साइन-अप और फोन वेरिफिकेशन के बाद आपके दोस्त को ₹30 मिलते हैं।',
    istep3: 'स्टेप 3- जब आपका दोस्त रिचार्ज करता है तो आपको ₹200 मिलते हैं।',
    notes: 'टिप्पणियाँ',
    inite1:
      'आपका मित्र ऐप का पहली बार उपयोगकर्ता होना चाहिए और उसे अपना पहला रिचार्ज करने से पहले आपका रेफ़रल कोड जोड़ना होगा।',
    inite2:
      'एक बार जब आपका दोस्त अपना पहला रिचार्ज कर लेगा तो आपको बोनस मिलेगा। ',
    inite3:
      'अगर आपका दोस्त अपना पहला रीचार्ज करने से पहले आपके रेफ़रल कोड का इस्तेमाल नहीं करता है, तो आपको ऑफ़र का लाभ नहीं मिलेगा',
  },
  bn: {},

  kn: {},
  en: {
    puja: 'Puja',
    reschedule: 'Reschedule',
    cancel: 'Cancel',
    amountpaid: 'Amount Paid',
    book: 'Book',
    prefer: 'Preferred Mode of Contact',
    pplease1:
      'Please provide the following information about the person you are taking the appointment for.',
    proceed: 'PROCEED',
    changeslot: 'Do you want to change the slot?',
    bookan: 'Book An Astrologer',
    consultan: 'Consult an Astrologer using three Easy Steps',
    signupwith: 'Sign Up with AstroUrjaa',
    bookan: 'Book an Appointment',
    getacallback: 'Get a Call Back',
    explore: 'Explore and book an appointment with our Astrologers',
    confirm: 'Confirmation',
    bookigsucessful: 'Booking successful for Online Puja',
    bookigsucessful1: 'Booking successful',
    referenceid: 'Your Booking Reference ID',
    youwillget: 'You will get a confirmation mail from AstroUrjaa Team',
    yes: 'Yes',
    iconfirm: 'I Confirm I have verified the data above and it is accurate.',
    iam18: 'I am 18 and Above ',
    ihaveunderstood: 'I have read & understood the',
    onlinepujabookig: 'Online Puja Booking',
    pplease:
      'Please provide the following information about the person you are booking online puja',
    book: 'Book',
    select: 'SELECT',
    purohit: "Purohit's",
    thankyou: 'Thank You !',
    busy: 'Astrologer is currently Busy. Please choose another astrologer or wait for sometime and re-initiate the consultation',
    offline:
      'Astrologer is currently Offline. Please choose another astrologer or wait for sometime and re-initiate the consultation',
    ok: 'OK',
    refer: 'Your friend gets ₹ 30 after Referral',
    enter: 'Enter Your Referral Code',
    ask: 'Ask your family or friends for referral code',
    submit: 'SUBMIT',
    contactus: 'Contact Us',
    emailus: 'Email Us',
    whatsappchat: 'WhatsApp Chat',
    callus: 'Call us 24/7 we will answer you',
    getsolution: 'Get Solution beamed to your inbox',
    startaconverstion: 'Start a conversation with WhatsApp now',
    formore: 'For more information, drop an email at',
    faq: "FAQ's",
    howsignup: 'How can I sign up?',
    step1: 'Step 1- Open the app and click on Sign Up.',
    step2:
      'Step 2- Enter the mobile number you want to register on AstroUrjaa.',
    step3:
      'Step 3- Click on Sign up and enter the OTP that you will receive via SMS on the mobile number. ',
    step4:
      "Once you have successfully signed up, you can fill in the required details and start consulting India's best astrologers",
    contactus: 'Contact Us',
    howitwork: 'How it Work ?',
    support: 'Support',
    callus1: 'Call Us',
    follow: 'Follow',
    followed: 'Following',
    invite: 'Invite and Earn',
    freebalance: 'free balance',
    sharelink:
      'Share the link with your friends and family, you both will be rewarded.',
    yourrefer: 'Your referral code is',
    invitevia: 'or Invite Via',
    inviteviasms: 'Invite Via Sms',
    refer3: 'Refer and Earn in 3 easy Step',
    istep1: 'Step 1-Invite a friend.',
    istep2: 'Step 2- Your friend gets ',

    istep3: 'Step 3- You get',
    after: 'after sign-up and phone verification.',
    isstep31: 'when your friend recharges.',
    notes: 'Notes',
    inite1:
      'Your friend must be a first-time user of the app and he/she must add your referral code before doing their first recharge. ',
    inite2:
      'Once your friend does their first recharge then you will get bonus. ',
    inite3:
      'If your friend doesn,t use your referral code before doing their first recharge then you wont get the offer benifits',
  },
  ta: {},
});

export default stringsoflanguagess;
