import LocalizedStrings from 'react-native-localization';
let stringsoflanguages = new LocalizedStrings({
  hi: {
    Availability: 'उपलब्धता',
    astrologerRegistration: 'Astrologer Registration',
    recharge: 'फिर से दाम लगाना',
    sendgift: 'उपहार भेजें',
    sendagift: 'एक उपहार भेजना',
    gift: 'उपहार',
    notification: 'सूचनाएं',
    about: 'के बारे में',
    year: 'साल',
    skip: 'छोड़ें',
    reviews: 'समीक्षा',
    mobile: 'मोबाइल',
    wewill: 'हम आपको आपके फ़ोन नंबर पर वन टाइम कोड भेजेंगे',
    agree: 'आप एस्ट्रोज्योतिष से सहमत हैं',
    terms: 'नियम और शर्तें',
    and: 'तथा',
    privacy: 'गोपनीयता नीति',
    getotp: 'ओटीपी प्राप्त करें',
    connect: 'या कनेक्ट',
    facebook: 'फेस्बूक के साथ साइन अप करें',
    google: 'Google के साथ साइन अप करें',
    enter: 'मोबाइल नंबर दर्ज करें',
    pleaseenter: 'कृपया मोबाइल नंबर दर्ज करें',
    accepttc: 'कृपया हमारे नियम और शर्तें और गोपनीयता नीति स्वीकार करें',
    verification: 'सत्यापन',
    smsotp: 'आपको एसएमएस के जरिए एक ओटीपी मिलेगा',
    verify: 'सत्यापित करना',
    didnt: 'सत्यापन ओटीपी प्राप्त नहीं हुआ?',
    resendagain: 'दोबारा भेजें',
    pleaseenterver: 'कृपया सत्यापन कोड दर्ज करें',
    verificationsendonmobile: 'आपके मोबाइल पर सत्यापन कोड भेज दिया गया है।',
    userregistration: 'उपयोगकर्ता का पंजीकरण',
    name: 'नाम',
    mailid: 'मेल आईडी',
    gender: 'लिंग',
    male: 'पुरुष',
    female: 'मादा',
    others: 'अन्य',
    dob: 'जन्म की तारीख',
    tob: 'जन्म का समय',
    pob: 'जन्म स्थान',
    address: 'पता',
    marital: 'वैवाहिक स्थिति',
    enterpartnerdetail: 'वैवाहिक स्थिति',
    pname: 'साथी का नाम',
    pdob: 'साथी की जन्म तिथि',
    ptob: 'साथी का जन्म समय',
    ppob: 'साथी का जन्म स्थान',
    create: 'सृजन करना',
    mywallet: 'मेरा बटुआ',
    walletbalance: 'वॉलेट बैलेंस',
    consultationhistory: 'वॉलेट लेन-देन इतिहास',
    choosea: 'उपलब्ध रिचार्ज पैक में से चुनें',
    extra: 'अतिरिक्त',
    rechargepack:
      'आपके रिचार्ज पैक का उपयोग कई ज्योतिषियों के लिए किया जा सकता है।',
    proceed: 'चुकाने के लिए कार्रवाई शुरू करो',
    pleaseselectamount: 'कृपया रिचार्ज करने के लिए राशि का चयन करें',
    paymentdetail: 'भुगतान विवरण',
    totalamount: 'कुल राशि',
    gst: 'जीएसटी',
    totalpayable: 'कुल देय राशि',
    couponcode: 'कूपन कोड',
    apply: 'लागू',
    recommended: 'अनुशंसित तरीके',
    paymentmethod: 'भुगतान की विधि',
    bonus: 'बक्शीश',
    onr: 'रिचार्ज राशि पर',
    balanceafter: 'रिचार्ज के बाद आपके वॉलेट में बैलेंस',
    paytm: 'पेटीएम',
    upi: 'यूपीआई',
    rupay: 'रुपे',
    debitcard: 'डेबिट कार्ड',
    creditcard: 'क्रेडिट कार्ड',
    paypal: 'पेपाल',
    netbanking: 'नेटबैंकिंग',
    cred: 'Cred',
    freecharge: 'फ्रीचार्ज',
    walletTransaction: 'वॉलेट लेनदेन',
    confirmation: 'पुष्टीकरण',
    rechargesucessfully: 'रिचार्ज सफल',
    continue: 'जारी रखें',
    search: 'खोज',
    chat: 'बात करना',
    call: 'बुलाना',
    video: 'वीडियो',
    booking: 'बुकिंग',
    astrologer: 'ज्योतिषी',
    onlinepuja: 'ऑनलाइन पूजा',
    blog: 'ब्लॉग',
    astrovideos: 'एस्ट्रोज्योतिष वीडियो',
    astronews: 'समाचार में एस्ट्रोज्योतिष',
    freeservice: 'मुफ्त सेवाएं',
    shareyourfeedback:
      'ऐप को बेहतर बनाने में हमारी मदद करने के लिए अपनी प्रतिक्रिया साझा करें',
    typereview: 'अपनी समीक्षा लिखें...',
    submit: 'प्रस्तुत',
    private: 'निजी और गोपनीय',
    verified: 'सत्यापित ज्योतिषी',
    secure: 'सुरक्षित भुगतान',
    kundali: 'कुण्डली',
    matchmaking: 'मैच बनाना',
    festival: 'समारोह',
    panchang: 'पंचांग',
    puja: 'ऑनलाइन पूजा आपकी आवश्यकताओं और आवश्यकता के आधार पर सभी प्रकार की पूजा सेवा प्रदान करने के लिए समर्पित है। अपनी तिथि और समय की बुकिंग के बाद, आपको पूजा सामग्री (जैसे चीनी, छोटी मूर्ति, दूध, आदि) के निर्देशों का एक सेट प्राप्त होगा और साथ ही आपके लिए कुछ सरल निर्देश (जैसे स्वच्छ भोजन, शराब नहीं) प्राप्त होंगे। अविश्वसनीय उपचार ऊर्जा जो पूजा के दौरान प्रसारित की जाएगी।',
    applanguage: 'अपनी ऐप भाषा चुनें',
    english: 'अंग्रेज़ी',
    tamil: 'तामिल',
    hindi: 'हिन्दी',
    kannada: 'कन्नडा',
    telegu: 'तेलुगू',
    bangla: 'बांग्ला',
    astrologerDetail: 'ज्योतिषी विवरण',
    readmore: 'अधिक पढ़ें',
    showless: 'कम दिखाएं',
    chatwith: 'ज्योतिषी के साथ चैट करें',
    talkwith: 'ज्योतिषी से बात करें',
    videowith: 'ज्योतिषी के साथ वीडियो कॉल',
    astrologers: 'ज्योतिषियों',
    myaccount: 'मेरा खाता',
    profile: 'प्रोफ़ाइल',
    customerSupport: 'ग्राहक सहेयता',
    edit: 'संपादन करना',
    share: 'शेयर करना',
    consulationsummary: 'परामर्श सारांश',
    logout: 'लॉग आउट',
    paymenthistory: 'भुगतान इतिहास',
    orderhistory: 'आदेश इतिहास',
    getReport: 'रिपोर्ट प्राप्त करें',
    enterreferalcode: 'रेफरल कोड दर्ज करें',
    status: 'दर्जा',
    callrate: 'कॉल दर',
    duration: 'अवधि',
    deduction: 'कटौती',
    createprofile: 'प्रोफ़ाइल बनाने',
    update: 'अद्यतन',
    show: 'प्रदर्शन',
    resetall: 'रीसेट करें',
    boydetail: 'लड़के का विवरण',
    girldetail: 'लड़की का विवरण',
    matchoroscope: 'कुंडली मिलान',
    isrequired: 'आवश्यक है',
    compatibilty: 'संगतता स्कोर',
    conclusion: 'एस्ट्रोज्योतिष निष्कर्ष',
    getKundali: 'कुंडली देखें',
    sharemy: 'मेरा मैच साझा करें',
    consultwith: 'ज्योतिषी से परामर्श करें',
    yourastrodetail: 'आपका एस्ट्रो विवरण',
    kundalichart: 'कुंडली चार्ट',
    doshareports: 'दोसा रिपोर्ट',
    remedies: 'उपचार',
    numerlogyreport: 'अंक ज्योतिष रिपोर्ट',
    destinityno: 'भाग्य संख्या',
    radicalno: 'रेडिकल नं',
    namenumber: 'नाम संख्या',
    evilnumber: 'दुष्ट संख्या',
    yourname: 'तुम्हारा  नाम',
    todayDate: 'आज की तारीख़',
    raicalruler: 'कट्टरपंथी शासक',
    friendlynumber: 'दोस्ताना संख्या',
    neutralday: 'तटस्थ दिन',
    favorabledays: 'अनुकूल दिन',
    favourablestone: 'अनुकूल पत्थर',
    favouabkesubstone: 'अनुकूल उपरत्न',
    favourableGod: 'अनुकूल देव',
    favourableMetal: 'अनुकूल धातु',
    favorableColor: 'अनुकूल रंग',
    favourablemantra: 'अनुकूल मंत्र',
    yourlifestone: 'आपका जीवन रत्न',
    yourbeneficstone: 'आपका लाभकारी रत्न',
    yourluckystone: 'आपका लकी स्टोन',
    subsitute: 'स्थानापन्न',
    finger: 'उँगलिया',
    weight: 'वज़न',
    day: 'दिन',
    diety: 'देवता',
    metal: 'धातु',
    birthchart: 'जन्म चार्ट',
    chalitchart: 'चलित चार्ट',
    moonchart: 'चंद्र चार्ट',
    sunchart: 'सन चार्ट',
    horachart: 'होरा चार्ट',
    dreskhanchart: 'द्रेष्कन चार्ट',
    chaturchart: 'चतुर्थमाश चार्ट',
    panchmanshachart: 'पंचमांश चार्ट',
    saptmanshachart: 'सप्तमांश चार्ट',
    asthamanshachart: 'अष्टमांश चार्ट',
    navmanshachart: 'नवमांश चार्ट',
    dashmanshachart: 'दशमांश चार्ट',
    dwadashachart: 'द्वादश चार्ट',
    shodashamnshachart: 'षोडशांश चार्ट',
    vishmnashachart: 'विषमांश चार्ट',
    chaturmanshachat: 'चतुर्विंशांश चार्ट',
    bhamshachart: 'भामशा चार्ट',
    trishamanshachart: 'त्रिशमांश चार्ट',
    khavedamshachart: 'खवेदांश चार्ट',
    akshvedanshachart: 'अक्षवेदांश चार्ट',
    shashtymshachart: 'षष्ट्यांश चार्ट',
    kalsarpd: 'कालसर्प दोष',
    mangalikd: 'मांगलिक दोष',
    sadesatidosha: 'साढ़ेसाती दोष',
    sdate: 'दिनांक',
    moonsign: 'राशि',
    saturnsign: 'शनि चिन्ह',
    retro: 'रेट्रो',
    type: 'टाइप',
    sldetail: 'साढ़ेसाती जीवन विवरण',
    sign: 'संकेत',
    platnet: 'ग्रहों',
    horoscopechart: 'आपका राशिफल चार्ट',
    hm: 'हिंदू माह और वर्ष',
    vikram: 'विक्रम संवत',
    shaka: 'शाखा संवत',
    paksha: 'पक्ष',
    ayana: 'अयाना',
    purnimanta: 'पूर्णिमांत',
    amanta: 'अमंता',
    sumsign: 'रवि चिन्ह',
    panchangelement: 'पंचांग तत्व',
    tithi: 'तिथि',
    nakshtra: 'नक्षत्र',
    yog: 'योग',
    karan: 'करण',
    upto: 'तक',
    basicdetail: 'मूल विवरण',
    sunrise: 'सूर्य उदय',
    sunset: 'सूर्यास्त',
    moonrise: 'चंद्र उदय',
    moonset: 'चंद्र अस्त',
    hindusunrise: 'हिंदू सूर्योदय',
    hindusunset: 'हिंदू सूर्यास्त',
    changeDetail: 'विवरण बदलें',
    panchangfor: 'पंचांग के लिए',
    panchangDetail: 'पंचांग विवरण',
    horamau: 'होरा मुहूर्त',
    chaugidya: 'चौघड़िया मुहूर्त',
    daychaugidiya: 'दिन चौघड़िया',
    nightchau: 'रात चौघड़िया',
    dayhora: 'दिन की होरा',
    nighthora: 'रात्रि होरा',
    ritu: 'रितु',
  },
  bn: {
    Availability: 'উপস্থিতি',
    astrologerRegistration: 'Astrologer Registration',
    recharge: 'রিচার্জ',
    sendgift: 'উপহার পাঠাও',
    sendagift: 'একটা উপহার পাঠাও',
    gift: 'উপহার',
    notification: 'বিজ্ঞপ্তি',
    about: 'সম্পর্কিত',
    skip: 'এড়িয়ে যান',
    mobile: 'মুঠোফোন',
    wewill: 'আমরা আপনাকে আপনার ফোন নম্বরে এককালীন কোড পাঠাব',
    agree: 'আপনি জ্যোতিষ জ্যোতিষের সাথে একমত',
    terms: 'শর্তাবলী',
    and: 'এবং',
    privacy: 'গোপনীয়তা নীতি',
    getotp: 'OTP পান',
    connect: 'অথবা সংযোগ করুন',
    facebook: 'ফেসবুক দিয়ে সাইন আপ',
    google: 'Google এর সাথে সাইন আপ করুন',
    enter: 'মোবাইল নম্বর লিখুন',
    pleaseenter: 'মোবাইল নম্বর লিখুন',
    accepttc: 'অনুগ্রহ করে আমাদের শর্তাবলী এবং গোপনীয়তা নীতি গ্রহণ করুন',
    verification: 'প্রতিপাদন',
    smsotp: 'আপনি SMS এর মাধ্যমে একটি OTP পাবেন',
    verify: 'যাচাই করুন',
    didnt: 'যাচাইকরণ ওটিপি পাননি?',
    resendagain: 'আবার পাঠান',
    pleaseenterver: 'যাচাইকরণ কোড লিখুন দয়া করে',
    verificationsendonmobile: 'আপনার মোবাইলে ভেরিফিকেশন কোড পাঠানো হয়েছে।',
    userregistration: 'মন্দ একটি নতুন শত্রু আছে',
    name: 'নাম',
    mailid: 'মেইল আইডি',
    gender: 'লিঙ্গ',
    male: 'পুরুষ',
    female: 'মহিলা',
    others: 'অন্যান্য',
    dob: 'জন্ম তারিখ',
    tob: 'জন্মের সময়',
    pob: 'জন্মস্থান',
    address: 'ঠিকানা',
    marital: 'বৈবাহিক অবস্থা',
    enterpartnerdetail: 'অংশীদারের বিবরণ লিখুন',
    pname: 'সঙ্গীর নাম',
    pdob: 'সঙ্গীর জন্ম তারিখ',
    ptob: 'সঙ্গীর জন্মের সময়',
    ppob: 'সঙ্গীর জন্মস্থান',
    create: 'সৃষ্টি',
    mywallet: 'আমার মানিব্যাগ',
    walletbalance: 'ওয়ালেট ব্যালেন্স',
    consultationhistory: 'ওয়ালেট লেনদেনের ইতিহাস',
    choosea: 'উপলব্ধ রিচার্জ প্যাক থেকে বেছে নিন',
    extra: 'অতিরিক্ত',
    rechargepack:
      'আপনার রিচার্জ প্যাক একাধিক জ্যোতিষীদের জন্য ব্যবহার করা যেতে পারে।',
    proceed: 'পে করতে এগিয়ে যান',
    pleaseselectamount: 'রিচার্জ করার জন্য অনুগ্রহ করে পরিমাণ নির্বাচন করুন',
    paymentdetail: 'পেমেন্ট বিবরণ',
    totalamount: 'সর্বমোট পরিমাণ',
    gst: 'জিএসটি',
    totalpayable: 'মোট প্রদেয় পরিমাণ',
    couponcode: 'কুপন কোড',
    apply: 'আবেদন করুন',
    recommended: 'প্রস্তাবিত পদ্ধতি',
    paymentmethod: 'মুল্য পরিশোধ পদ্ধতি',
    bonus: 'বোনাস',
    onr: 'রিচার্জ পরিমাণে',
    balanceafter: 'রিচার্জের পর আপনার ওয়ালেটে ব্যালেন্স রাখুন',
    paytm: 'পেটিএম',
    upi: 'ইউপিআই',
    rupay: 'রুপে',
    debitcard: 'ডেবিট কার্ড',
    creditcard: 'ক্রেডিট কার্ড',
    paypal: 'Paypal',
    netbanking: 'নেটব্যাংকিং',
    cred: 'ক্রেড',
    freecharge: 'ফ্রিচার্জ',
    walletTransaction: 'ওয়ালেট লেনদেন',
    confirmation: 'নিশ্চিতকরণ',
    rechargesucessfully: 'রিচার্জ সফল',
    continue: 'চালিয়ে যান',
    search: 'অনুসন্ধান করুন',
    chat: 'চ্যাট',
    call: 'কল',
    video: 'ভিডিও',
    booking: 'সংরক্ষণ',
    astrologer: 'জ্যোতিষীর',
    onlinepuja: 'অনলাইন পুজো',
    blog: 'ব্লগ',
    astrovideos: 'AstroUrjaa ভিডিও',
    astronews: 'খবরে জ্যোতিষ জ্যোতিষ',
    freeservice: 'বিনামূল্যে সেবা',
    shareyourfeedback:
      'অ্যাপটি উন্নত করতে আমাদের সাহায্য করতে আপনার প্রতিক্রিয়া শেয়ার করুন',
    typereview: 'আপনার পর্যালোচনা টাইপ করুন...',
    submit: 'জমা দিন',
    private: 'ব্যক্তিগত ও গোপনীয়',
    verified: 'যাচাইকৃত জ্যোতিষী',
    secure: 'নিরাপদ পেমেন্ট',
    kundali: 'কুণ্ডলী',
    matchmaking: 'ম্যাচ মেকিং',
    festival: 'উৎসব',
    panchang: 'পঞ্চং',
    applanguage: 'আপনার অ্যাপের ভাষা চয়ন করুন',
    english: 'ইংরেজি',
    tamil: 'তামিল',
    hindi: 'হিন্দি',
    kannada: 'কন্নড়',
    telegu: 'তেলেগু',
    bangla: 'বাংলা',
    reviews: 'রিভিউ',
    puja: 'অনলাইন পূজা আপনার প্রয়োজন এবং প্রয়োজনের উপর নির্ভর করে সমস্ত ধরণের পূজা পরিষেবা প্রদানের জন্য নিবেদিত। আপনার তারিখ এবং সময় বুক করার পরে, আপনি পূজার উপকরণ সংগ্রহ করার জন্য নির্দেশাবলীর একটি সেট পাবেন (যেমন চিনি, ছোট প্রতিমা, দুধ, ইত্যাদি) পাশাপাশি কিছু সহজ নির্দেশনা (যেমন পরিষ্কার খাওয়া, অ্যালকোহল না) আপনি সর্বাধিক করতে পারবেন। অবিশ্বাস্য নিরাময় শক্তি যা পূজার সময় প্রেরণ করা হবে।',
    astrologerDetail: 'জ্যোতিষীর বিবরণ',
    readmore: 'আরও পড়ুন',
    showless: 'প্রদর্শন কম',
    year: 'বছর',
    chatwith: 'Astroger এর সাথে চ্যাট করুন',
    talkwith: 'জ্যোতিষীর সাথে কথা বলুন',
    videowith: 'জ্যোতিষীর সাথে ভিডিও কল',
    astrologers: 'জ্যোতিষী',
    myaccount: 'আমার অ্যাকাউন্ট',
    profile: 'প্রোফাইল',
    customerSupport: 'গ্রাহক সমর্থন',
    edit: 'সম্পাদনা করুন',
    share: 'শেয়ার করুন',
    consulationsummary: 'পরামর্শের সারাংশ',
    logout: 'প্রস্থান',
    paymenthistory: 'অর্থ প্রদান ইতিহাস',
    orderhistory: 'অর্ডার ইতিহাস',
    getReport: 'রিপোর্ট পান',
    enterreferalcode: 'রেফারেল কোড লিখুন',
    status: 'স্ট্যাটাস',
    callrate: 'কল রেট',
    duration: 'সময়কাল',
    deduction: 'ডিডাকশন',
    createprofile: 'প্রোফাইল তৈরি করুন',
    update: 'হালনাগাদ',
    show: 'দেখান',
    resetall: 'Reset All',
    boydetail: 'ছেলের বিস্তারিত',
    girldetail: 'মেয়ের বিস্তারিত',
    matchoroscope: 'মেল রাশিফল',
    isrequired: 'দরকার',
    compatibilty: 'সামঞ্জস্যপূর্ণ স্কোর',
    conclusion: 'জ্যোতিষ জ্যোতিষ উপসংহার',
    getKundali: 'কুন্ডলি দেখুন',
    sharemy: 'আমার ম্যাচ শেয়ার করুন',
    consultwith: 'জ্যোতিষীর সাথে পরামর্শ করুন',
    yourastrodetail: 'আপনার Astro বিবরণ',
    kundalichart: 'কুন্ডলি চার্ট',
    doshareports: 'দোশা রিপোর্ট',
    remedies: 'প্রতিকার',
    numerlogyreport: 'সংখ্যাতত্ত্ব রিপোর্ট',
    destinityno: 'ডেসটিনি নং',
    radicalno: 'র্যাডিক্যাল নং',
    namenumber: 'নাম নম্বর',
    evilnumber: 'মন্দ নম্বর',
    yourname: 'তোমার নাম',
    todayDate: 'আজকের তারিখ',
    raicalruler: 'মৌলবাদী শাসক',
    friendlynumber: 'বন্ধুত্বপূর্ণ নম্বর',
    neutralday: 'নিরপেক্ষ দিন',
    favorabledays: 'অনুকূল দিন',
    favourablestone: 'অনুকূল পাথর',
    favouabkesubstone: 'অনুকূল সাব স্টোন',
    favourableGod: 'অনুকূল ঈশ্বর',
    favourableMetal: 'অনুকূল ধাতু',
    favorableColor: 'অনুকূল রং',
    favourablemantra: 'অনুকূল মন্ত্র',
    yourlifestone: 'আপনার জীবন পাথর',
    yourbeneficstone: 'আপনার উপকারী পাথর',
    yourluckystone: 'তোমার লাকি স্টোন',
    subsitute: 'বিকল্প',
    finger: 'আঙুল',
    weight: 'ওজন',
    day: 'দিন',
    diety: 'ডায়েটি',
    metal: 'ধাতু',
    birthchart: 'জন্ম তালিকা',
    chalitchart: 'চলিত চার্ট',
    moonchart: 'চাঁদের চার্ট',
    sunchart: 'সূর্যের চার্ট',
    horachart: 'হোরা চার্ট',
    dreskhanchart: 'ড্রেশকান চার্ট',
    chaturchart: 'চতুর্থমশা চার্ট',
    panchmanshachart: 'পঞ্চমাংশ চার্ট',
    saptmanshachart: 'সপ্তমাংশ চার্ট',
    asthamanshachart: 'অষ্টমাংশ চার্ট',
    navmanshachart: 'নবমাংশ চার্ট',
    dashmanshachart: 'দশমাংশ চার্ট',
    dwadashachart: 'দ্বাদশ চার্ট',
    shodashamnshachart: 'ষোদশাংশ চার্ট',
    vishmnashachart: 'বিষমাংশ চার্ট',
    chaturmanshachat: 'চতুর্ভিমাংশ চার্ট',
    bhamshachart: 'ভামশা চার্ট',
    trishamanshachart: 'ত্রিশামংশ চার্ট',
    khavedamshachart: 'খাভেদমশা চার্ট',
    akshvedanshachart: 'অক্ষবেদংশ চার্ট',
    shashtymshachart: 'ষষ্টিমশা চার্ট',
    kalsarpd: 'কালসর্প দোষ',
    mangalikd: 'মাঙ্গলিক দোষ',
    sadesatidosha: 'সাধেসতী দোষ',
    sdate: 'তারিখ',
    moonsign: 'চাঁদের চিহ্ন',
    saturnsign: 'শনি চিহ্ন',
    retro: 'বিপরীতমুখী',
    type: 'টাইপ',
    sldetail: 'সাধেসাটি জীবনের বিস্তারিত',
    sign: 'চিহ্ন',
    platnet: 'গ্রহ',
    horoscopechart: 'আপনার রাশিফল ​​চার্ট',
    hm: 'হিন্দু মাস ও বছর',
    vikram: 'বিক্রম সংবত',
    shaka: 'শাখা সংবত',
    paksha: 'পাকশা',
    ayana: 'আয়না',
    purnimanta: 'পূর্ণিমন্ত',
    amanta: 'আমন্তা',
    sumsign: 'সূর্য চিহ্ন',
    panchangelement: 'পঞ্চং উপাদান',
    tithi: 'তিথি',
    nakshtra: 'নক্ষত্র',
    yog: 'যোগ',
    karan: 'করণ',
    upto: 'পর্যন্ত',
    basicdetail: 'মৌলিক বিবরণ',
    sunrise: 'সূর্যোদয়',
    sunset: 'সূর্যাস্ত',
    moonrise: 'চাঁদের উত্থান',
    moonset: 'চাঁদ সেট',
    hindusunrise: 'হিন্দু সূর্যোদয়',
    hindusunset: 'হিন্দু সূর্যাস্ত',
    changeDetail: 'বিবরণ পরিবর্তন করুন',
    panchangfor: 'পঞ্চাং ফর',
    panchangDetail: 'পঞ্চং বিস্তারিত',
    horamau: 'হোরা মুহুর্তা',
    chaugidya: 'চৌঘদিয়া মুহুর্তা',
    daychaugidiya: 'দিন চোৰাদিয়া',
    nightchau: 'রাত্রি চৌঘদিয়া',
    dayhora: 'দিন হোরা',
    nighthora: 'রাত হোরা',
    ritu: 'রিতু',
  },

  en: {
    Availability: 'Availability',
    astrologerRegistration: 'Astrologer Registration',
    recharge: 'Recharge',
    sendgift: 'Send Gift',
    sendagift: 'Send a Gift',
    gift: 'Gifts',
    notification: 'Notifications',
    skip: 'Skip',
    mobile: 'Mobile',
    wewill: 'We Will send you one time code on your phone number',
    agree: 'You Agree to AstroUrjaa',
    terms: 'Terms and Conditions',
    and: 'and',
    privacy: 'Privacy Policy',
    getotp: 'GET OTP',
    connect: 'or Connect',
    facebook: 'Sign Up With Facebook',
    google: 'Sign Up With Google',
    enter: 'Enter Mobile Number',
    pleaseenter: 'Please enter Mobile number',
    accepttc: 'Please accept our Terms and Conditions and Privacy Policy',
    verification: 'Verification',
    smsotp: 'You will get a OTP via SMS',
    verify: 'VERIFY',
    didnt: "Did't receive the verification OTP ?",
    resendagain: 'Resend Again',
    pleaseenterver: 'Please enter Verification Code',
    verificationsendonmobile: 'Verification code has been send on your Mobile.',
    userregistration: 'User Registration',
    name: 'Name',
    mailid: 'Mail ID',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    others: 'Others',
    dob: 'Date Of Birth',
    tob: 'Time Of Birth',
    pob: 'Place Of Birth',
    address: 'Address',
    marital: 'Marital Status',
    enterpartnerdetail: "Enter Partner's Details",
    pname: "Partner's Name",
    pdob: "Partner's Date Of Birth",
    ptob: "Partner's Time Of Birth",
    ppob: "Partner's Place Of Birth",
    create: 'CREATE',
    mywallet: 'My Wallet',
    walletbalance: 'Wallet Balance',
    consultationhistory: 'Wallet Transaction History',
    choosea: 'Choose from the available Recharge packs',
    extra: 'Extra',
    rechargepack: 'Your recharge pack can be used for multiple astrologers.',
    proceed: 'PROCEED TO PAY',
    pleaseselectamount: 'Please select amount to recharge',
    paymentdetail: 'Payment Details',
    totalamount: 'Total Amount',
    gst: 'GST',
    totalpayable: 'Total Payable Amount',
    couponcode: 'Coupon Code',
    apply: 'APPLY',
    recommended: 'Recommended Methods',
    paymentmethod: 'Payment Methods',
    bonus: 'Bonus',
    onr: 'on Recharge Amount',
    balanceafter: 'Balance on your wallet after recharge',
    paytm: 'Paytm',
    upi: 'UPI',
    rupay: 'RuPay',
    debitcard: 'Debit Card',
    creditcard: 'Credit Card',
    paypal: 'Paypal',
    netbanking: 'NetBanking',
    cred: 'Cred',
    freecharge: 'Freecharge',
    walletTransaction: 'Wallet Transaction',
    confirmation: 'Confirmation',
    rechargesucessfully: 'Recharge successful',
    continue: 'CONTINUE',
    search: 'Search',
    chat: 'Chat',
    call: 'Call',
    video: 'Video',
    booking: 'Booking',
    astrologer: "Astrologer's",
    onlinepuja: 'Online Puja',
    blog: 'Blog',
    astrovideos: 'AstroUrjaa Videos',
    astronews: 'AstroUrjaa in News',
    freeservice: 'Free Services',
    shareyourfeedback: 'Share your feedback to help us improve the app',
    typereview: 'Type your review ...',
    submit: 'SUBMIT',
    private: 'Private and Confidential',
    verified: 'Verified Astrologers',
    secure: 'Secure Payment',
    kundali: 'Kundali',
    matchmaking: 'Match Making',
    festival: 'Festivals',
    panchang: 'Panchang',
    applanguage: 'Choose your App Language',
    english: 'English',
    tamil: 'Tamil',
    hindi: 'Hindi',
    kannada: 'Kannada',
    telegu: 'Telegu',
    bangla: 'Bangla',
    reviews: 'Reviews',
    puja: 'Online puja is dedicated to provide all kind of Puja service depending on your needs and requirement. After booking your date and time, you will receive a set of instructions of puja materials to procure (e.g. sugar, small idol, milk, etc.) as well some simple instructions (e.g. clean eating, no alcohol) for you to make the most of the incredible healing energy that will be transmitted during the puja.',
    astrologerDetail: 'Astrologer Details',
    readmore: 'Read More',
    showless: 'Show Less',
    year: 'Year',
    chatwith: 'Chat With Astrolger',
    talkwith: 'Talk to Astrologer',
    videowith: 'Video Call with Astrologer',
    astrologers: 'Astrologers',
    myaccount: 'My Account',
    profile: 'Profile',
    customerSupport: 'Customer Support',
    edit: 'Edit',
    share: 'Share',
    consulationsummary: 'Consultation Summary',
    logout: 'Logout',
    paymenthistory: 'Payment History',
    orderhistory: 'Order History',
    getReport: 'Get Report',
    enterreferalcode: 'Enter Referral Code',
    status: 'Status',
    callrate: 'Call Rate',
    duration: 'Duration',
    deduction: 'Deduction',
    createprofile: 'Create Profile',
    update: 'Update',
    show: 'Show',
    resetall: 'Reset All',
    boydetail: "Boy's Detail",
    girldetail: "Girl's Detail",
    matchoroscope: 'Match Horoscope',
    isrequired: 'Is Required',
    compatibilty: 'Compatiblity Score',
    conclusion: 'AstroUrjaa Conclusion',
    getKundali: 'VIEW KUNDALI',
    sharemy: 'SHARE MY MATCH',
    consultwith: 'CONSULT WITH ASTROLOGER',
    yourastrodetail: 'Your Astro Details',
    kundalichart: 'Kundali Charts',
    doshareports: 'Dosha Reports',
    remedies: 'Remedies',
    numerlogyreport: 'Numerology Reports',
    destinityno: 'Destiny No',
    radicalno: 'Radical No',
    namenumber: 'Name Number',
    evilnumber: 'Evil Number',
    yourname: 'Your Name',
    todayDate: 'Today Date',
    raicalruler: 'Radical Ruler',
    friendlynumber: 'Friendly Number',
    neutralday: 'Neutral Days',
    favorabledays: 'Favourable Days',
    favourablestone: 'Favourable Stone',
    favouabkesubstone: 'Favourable Sub Stone',
    favourableGod: 'Favourable God',
    favourableMetal: 'Favourable Metal',
    favorableColor: 'Favourable Color',
    favourablemantra: 'Favourable Mantra',
    yourlifestone: 'Your Life Stone',
    yourbeneficstone: 'Your Benefic Stone',
    yourluckystone: 'Your Lucky Stone',
    subsitute: 'Subsitute',
    finger: 'Finger',
    weight: 'Weight',
    day: 'Day',
    diety: 'Diety',
    metal: 'Metal',
    birthchart: 'Birth Chart',
    chalitchart: 'Chalit Chart',
    moonchart: 'Moon Chart',
    sunchart: 'Sun Chart',
    horachart: 'Hora Chart',
    dreskhanchart: 'Dreshkan Chart',
    chaturchart: 'Chaturthamasha Chart',
    panchmanshachart: 'Panchmansha Chart',
    saptmanshachart: 'Saptamansha Chart',
    asthamanshachart: 'Ashtamansha Chart',
    navmanshachart: 'Navamansha Chart',
    dashmanshachart: 'Dashamansha Chart',
    dwadashachart: 'Dwadasha Chart',
    shodashamnshachart: 'Shodashamsha Chart',
    vishmnashachart: 'Vishamansha Chart',
    chaturmanshachat: 'Chaturvimshamsha Chart',
    bhamshachart: 'Bhamsha Chart',
    trishamanshachart: 'Trishamansha Chart',
    khavedamshachart: 'Khavedamsha Chart',
    akshvedanshachart: 'Akshvedansha Chart',
    shashtymshachart: 'Shashtymsha Chart',
    kalsarpd: 'Kalsarpa Dosha',
    mangalikd: 'Mangalik Dosha',
    sadesatidosha: 'SadheSati Dosha',
    sdate: 'Date',
    moonsign: 'Moon Sign',
    saturnsign: 'Saturn Sign',
    retro: 'Retro',
    type: 'Type',
    sldetail: 'Sadhesati Life Details',
    sign: 'Sign',
    platnet: 'Planets',
    horoscopechart: 'Your Horoscope Chart',
    hm: 'Hindu Month & Year',
    vikram: 'Vikram Samvat',
    shaka: 'Shakha Samvat',
    paksha: 'Paksha',
    ayana: 'Ayana',
    purnimanta: 'Purnimanta',
    amanta: 'Amanta',
    sumsign: 'Sun Sign',
    panchangelement: 'Panchang Elements',
    tithi: 'Tithi',
    nakshtra: 'Nakshatra',
    yog: 'Yog',
    karan: 'Karan',
    upto: 'Upto',
    basicdetail: 'Basic Details',
    sunrise: 'Sun Rise',
    sunset: 'Sun Set',
    moonrise: 'Moon Rise',
    moonset: 'Moon Set',
    hindusunrise: 'Hindu Sunrise',
    hindusunset: 'Hindu Sunset',
    changeDetail: 'Change Details',
    panchangfor: 'Panchang For',
    panchangDetail: 'Panchang Details',
    horamau: 'Hora Muhurta',
    chaugidya: 'Chaughadiya Muhurta',
    daychaugidiya: 'Day Chaughadiya',
    nightchau: 'Night Chaughadiya',
    dayhora: 'Day Hora',
    nighthora: 'Night Hora',
    ritu: 'Ritu',
    about: 'About',
  },

  kn: {
    Availability: 'ಲಭ್ಯತೆ',
    astrologerRegistration: 'Astrologer Registration',
    recharge: 'ರೀಚಾರ್ಜ್ ಮಾಡಿ',
    sendgift: 'ಉಡುಗೊರೆ ಕಳುಹಿಸಿ',
    sendagift: 'ಉಡುಗೊರೆಯನ್ನು ಕಳುಹಿಸಿ',
    gift: 'ಉಡುಗೊರೆಗಳು',
    notification: 'ಅಧಿಸೂಚನೆಗಳು',
    about: 'ಬಗ್ಗೆ',
    skip: 'ಬಿಟ್ಟುಬಿಡಿ',
    mobile: 'ಮೊಬೈಲ್',
    wewill:
      'ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆಗೆ ನಾವು ನಿಮಗೆ ಒಂದು ಬಾರಿಯ ಕೋಡ್ ಅನ್ನು ಕಳುಹಿಸುತ್ತೇವೆ',
    agree: 'ನೀವು AstroUrjaa ಗೆ ಒಪ್ಪುತ್ತೀರಿ',
    terms: 'ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು',
    and: 'ಮತ್ತು',
    privacy: 'ಗೌಪ್ಯತಾ ನೀತಿ',
    getotp: 'OTP ಪಡೆಯಿರಿ',
    connect: 'ಅಥವಾ ಸಂಪರ್ಕಿಸಿ',
    facebook: 'ಫೇಸ್ಬುಕ್ನೊಂದಿಗೆ ಸೈನ್ ಅಪ್ ಮಾಡಿ',
    google: 'Google ನೊಂದಿಗೆ ಸೈನ್ ಅಪ್ ಮಾಡಿ',
    enter: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
    pleaseenter: 'ದಯವಿಟ್ಟು ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
    accepttc:
      'ದಯವಿಟ್ಟು ನಮ್ಮ ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು ಮತ್ತು ಗೌಪ್ಯತಾ ನೀತಿಯನ್ನು ಒಪ್ಪಿಕೊಳ್ಳಿ',
    verification: 'ಪರಿಶೀಲನೆ',
    smsotp: 'ನೀವು SMS ಮೂಲಕ OTP ಅನ್ನು ಪಡೆಯುತ್ತೀರಿ',
    verify: 'ಪರಿಶೀಲಿಸಿ',
    didnt: 'ಪರಿಶೀಲನೆ OTP ಸ್ವೀಕರಿಸಲಿಲ್ಲವೇ?',
    resendagain: 'ಮತ್ತೆ ಕಳುಹಿಸಿ',
    pleaseenterver: 'ದಯವಿಟ್ಟು ಪರಿಶೀಲನೆ ಕೋಡ್ ನಮೂದಿಸಿ',
    verificationsendonmobile:
      'ಪರಿಶೀಲನೆ ಕೋಡ್ ಅನ್ನು ನಿಮ್ಮ ಮೊಬೈಲ್‌ಗೆ ಕಳುಹಿಸಲಾಗಿದೆ.',
    userregistration: 'ಬಳಕೆದಾರರ ನೋಂದಣಿ',
    name: 'ಹೆಸರು',
    mailid: 'ಮೇಲ್ ಐಡಿ',
    gender: 'ಲಿಂಗ',
    male: 'ಪುರುಷ',
    female: 'ಹೆಣ್ಣು',
    others: 'ಇತರರು',
    dob: 'ಹುಟ್ತಿದ ದಿನ',
    tob: 'ಹುಟ್ಟಿದ ಸಮಯ',
    pob: 'ಹುಟ್ಟಿದ ಸ್ಥಳ',
    address: 'ವಿಳಾಸ',
    marital: 'ವೈವಾಹಿಕ ಸ್ಥಿತಿ',
    enterpartnerdetail: 'ಪಾಲುದಾರರ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ',
    pname: 'ಪಾಲುದಾರರ ಹೆಸರು',
    pdob: 'ಪಾಲುದಾರರ ಜನ್ಮ ದಿನಾಂಕ',
    ptob: 'ಪಾಲುದಾರರ ಜನ್ಮ ಸಮಯ',
    ppob: 'ಪಾಲುದಾರರ ಜನ್ಮ ಸ್ಥಳ',
    create: 'ರಚಿಸಿ',
    mywallet: 'ನನ್ನ ಕೈಚೀಲ',
    walletbalance: 'ವಾಲೆಟ್ ಬ್ಯಾಲೆನ್ಸ್',
    consultationhistory: 'ವಾಲೆಟ್ ವಹಿವಾಟಿನ ಇತಿಹಾಸ',
    choosea: 'ಲಭ್ಯವಿರುವ ರೀಚಾರ್ಜ್ ಪ್ಯಾಕ್‌ಗಳಿಂದ ಆರಿಸಿಕೊಳ್ಳಿ',
    extra: 'ಹೆಚ್ಚುವರಿ',
    rechargepack: 'ನಿಮ್ಮ ರೀಚಾರ್ಜ್ ಪ್ಯಾಕ್ ಅನ್ನು ಬಹು ಜ್ಯೋತಿಷಿಗಳಿಗೆ ಬಳಸಬಹುದು.',
    proceed: 'ಪಾವತಿಸಲು ಮುಂದುವರಿಯಿರಿ',
    pleaseselectamount: 'ದಯವಿಟ್ಟು ರೀಚಾರ್ಜ್ ಮಾಡಲು ಮೊತ್ತವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    paymentdetail: 'ಪಾವತಿ ವಿವರಗಳು',
    totalamount: 'ಒಟ್ಟು ಮೊತ್ತ',
    gst: 'ಜಿಎಸ್ಟಿ',
    totalpayable: 'ಪಾವತಿಸಬೇಕಾದ ಒಟ್ಟು ಮೊತ್ತ',
    couponcode: 'ಕೂಪನ್ ಕೋಡ್',
    apply: 'ಅನ್ವಯಿಸು',
    recommended: 'ಶಿಫಾರಸು ವಿಧಾನಗಳು',
    paymentmethod: 'ಪಾವತಿ ವಿಧಾನಗಳು',
    bonus: 'ಬೋನಸ್',
    onr: 'ರೀಚಾರ್ಜ್ ಮೊತ್ತದ ಮೇಲೆ',
    balanceafter: 'ರೀಚಾರ್ಜ್ ಮಾಡಿದ ನಂತರ ನಿಮ್ಮ ವ್ಯಾಲೆಟ್‌ನಲ್ಲಿ ಬ್ಯಾಲೆನ್ಸ್ ಮಾಡಿ',
    paytm: 'Paytm',
    upi: 'UPI',
    rupay: 'ರೂಪಾಯಿ',
    debitcard: 'ಡೆಬಿಟ್ ಕಾರ್ಡ್',
    creditcard: 'ಕ್ರೆಡಿಟ್ ಕಾರ್ಡ್',
    paypal: 'Paypal',
    netbanking: 'ನೆಟ್ ಬ್ಯಾಂಕಿಂಗ್',
    cred: 'ಕ್ರೆಡಿಟ್',
    freecharge: 'ಫ್ರೀಚಾರ್ಜ್',
    walletTransaction: 'ವಾಲೆಟ್ ವಹಿವಾಟು',
    confirmation: 'ದೃಢೀಕರಣ',
    rechargesucessfully: 'ರೀಚಾರ್ಜ್ ಯಶಸ್ವಿಯಾಗಿದೆ',
    continue: 'ಮುಂದುವರಿಸಿ',
    search: 'ಹುಡುಕಿ',
    chat: 'ಚಾಟ್ ಮಾಡಿ',
    call: 'ಕರೆ ಮಾಡಿ',
    video: 'ವೀಡಿಯೊ',
    booking: 'ಬುಕಿಂಗ್',
    astrologer: 'ಜ್ಯೋತಿಷಿಯ',
    onlinepuja: 'ಆನ್‌ಲೈನ್ ಪೂಜೆ',
    blog: 'ಬ್ಲಾಗ್',
    astrovideos: 'AstroUrjaa ವೀಡಿಯೊಗಳು',
    astronews: 'ಸುದ್ದಿಯಲ್ಲಿ ಆಸ್ಟ್ರೋಜ್ಯೋತಿಷ್',
    freeservice: 'ಉಚಿತ ಸೇವೆಗಳು',
    shareyourfeedback:
      'ಅಪ್ಲಿಕೇಶನ್ ಅನ್ನು ಸುಧಾರಿಸಲು ನಮಗೆ ಸಹಾಯ ಮಾಡಲು ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಹಂಚಿಕೊಳ್ಳಿ',
    typereview: 'ನಿಮ್ಮ ವಿಮರ್ಶೆಯನ್ನು ಟೈಪ್ ಮಾಡಿ...',
    submit: 'ಸಲ್ಲಿಸು',
    private: 'ಖಾಸಗಿ ಮತ್ತು ಗೌಪ್ಯ',
    verified: 'ಪರಿಶೀಲಿಸಿದ ಜ್ಯೋತಿಷಿಗಳು',
    secure: 'ಸುರಕ್ಷಿತ ಪಾವತಿ',
    kundali: 'ಕುಂಡಲಿ',
    matchmaking: 'ಮ್ಯಾಚ್ ಮೇಕಿಂಗ್',
    festival: 'ಹಬ್ಬಗಳು',
    panchang: 'ಪಂಚಾಂಗ',
    applanguage: 'ನಿಮ್ಮ ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆಯನ್ನು ಆರಿಸಿ',
    english: 'ಆಂಗ್ಲ',
    tamil: 'ತಮಿಳು',
    hindi: 'ಹಿಂದಿ',
    kannada: 'ಕನ್ನಡ',
    telegu: 'ತೆಲುಗು',
    bangla: 'ಬಾಂಗ್ಲಾ',
    reviews: 'ವಿಮರ್ಶೆಗಳು',
    puja: 'ನಿಮ್ಮ ಅಗತ್ಯತೆಗಳು ಮತ್ತು ಅವಶ್ಯಕತೆಗಳಿಗೆ ಅನುಗುಣವಾಗಿ ಎಲ್ಲಾ ರೀತಿಯ ಪೂಜೆ ಸೇವೆಯನ್ನು ಒದಗಿಸಲು ಆನ್‌ಲೈನ್ ಪೂಜೆಯನ್ನು ಸಮರ್ಪಿಸಲಾಗಿದೆ. ನಿಮ್ಮ ದಿನಾಂಕ ಮತ್ತು ಸಮಯವನ್ನು ಕಾಯ್ದಿರಿಸಿದ ನಂತರ, ನೀವು ಖರೀದಿಸಲು ಪೂಜಾ ಸಾಮಗ್ರಿಗಳ ಸೂಚನೆಗಳನ್ನು (ಉದಾ. ಸಕ್ಕರೆ, ಸಣ್ಣ ವಿಗ್ರಹ, ಹಾಲು, ಇತ್ಯಾದಿ) ಜೊತೆಗೆ ನೀವು ಹೆಚ್ಚು ಮಾಡಲು ಕೆಲವು ಸರಳ ಸೂಚನೆಗಳನ್ನು (ಉದಾಹರಣೆಗೆ ಸ್ವಚ್ಛವಾಗಿ ತಿನ್ನುವುದು, ಮದ್ಯಪಾನ ಮಾಡಬಾರದು) ಸ್ವೀಕರಿಸುತ್ತೀರಿ. ಪೂಜೆಯ ಸಮಯದಲ್ಲಿ ಹರಡುವ ನಂಬಲಾಗದ ಗುಣಪಡಿಸುವ ಶಕ್ತಿ.',
    astrologerDetail: 'ಜ್ಯೋತಿಷಿಯ ವಿವರಗಳು',
    readmore: 'ಮತ್ತಷ್ಟು ಓದು',
    showless: 'ಕಡಿಮೆ ತೋರಿಸು',
    year: 'ವರ್ಷ',
    chatwith: 'ಜ್ಯೋತಿಷಿಯೊಂದಿಗೆ ಚಾಟ್ ಮಾಡಿ',
    talkwith: 'ಜ್ಯೋತಿಷಿಯೊಂದಿಗೆ ಮಾತನಾಡಿ',
    videowith: 'ಜ್ಯೋತಿಷಿಯೊಂದಿಗೆ ವೀಡಿಯೊ ಕರೆ',
    astrologers: 'ಜ್ಯೋತಿಷಿಗಳು',
    myaccount: 'ನನ್ನ ಖಾತೆ',
    profile: 'ಪ್ರೊಫೈಲ್',
    customerSupport: 'ಗ್ರಾಹಕ ಬೆಂಬಲ',
    edit: 'ತಿದ್ದು',
    share: 'ಹಂಚಿಕೊಳ್ಳಿ',
    consulationsummary: 'ಸಮಾಲೋಚನೆಯ ಸಾರಾಂಶ',
    logout: 'ಲಾಗ್ ಔಟ್',
    paymenthistory: 'ಪಾವತಿ ಇತಿಹಾಸ',
    orderhistory: 'ಆದೇಶ ಇತಿಹಾಸ',
    getReport: 'ವರದಿ ಪಡೆಯಿರಿ',
    enterreferalcode: 'ರೆಫರಲ್ ಕೋಡ್ ನಮೂದಿಸಿ',
    status: 'ಸ್ಥಿತಿ',
    callrate: 'ಕರೆ ದರ',
    duration: 'ಅವಧಿ',
    deduction: 'ಕಡಿತಗೊಳಿಸುವಿಕೆ',
    createprofile: 'ಪ್ರೊಫೈಲ್ ರಚಿಸಿ',
    update: 'ನವೀಕರಿಸಿ',
    show: 'ತೋರಿಸು',
    resetall: 'ಎಲ್ಲಾ ಮರುಹೊಂದಿಸಿ',
    boydetail: 'ಹುಡುಗನ ವಿವರ',
    girldetail: 'ಹುಡುಗಿಯ ವಿವರ',
    matchoroscope: 'ಹೊಂದಾಣಿಕೆಯ ಜಾತಕ',
    isrequired: 'ಅಗತ್ಯವಿದೆ',
    compatibilty: 'ಹೊಂದಾಣಿಕೆ ಸ್ಕೋರ್',
    conclusion: 'ಆಸ್ಟ್ರೋಜ್ಯೋತಿಶ್ ತೀರ್ಮಾನ',
    getKundali: 'ಕುಂಡಲಿಯನ್ನು ವೀಕ್ಷಿಸಿ',
    sharemy: 'ನನ್ನ ಪಂದ್ಯವನ್ನು ಹಂಚಿಕೊಳ್ಳಿ',
    consultwith: 'ಜ್ಯೋತಿಷಿಯೊಂದಿಗೆ ಸಮಾಲೋಚಿಸಿ',
    yourastrodetail: 'ನಿಮ್ಮ ಆಸ್ಟ್ರೋ ವಿವರಗಳು',
    kundalichart: 'ಕುಂಡಲಿ ಚಾರ್ಟ್‌ಗಳು',
    doshareports: 'ದೋಷ ವರದಿಗಳು',
    remedies: 'ಪರಿಹಾರಗಳು',
    numerlogyreport: 'ಸಂಖ್ಯಾಶಾಸ್ತ್ರದ ವರದಿಗಳು',
    destinityno: 'ಡೆಸ್ಟಿನಿ ನಂ',
    radicalno: 'ರಾಡಿಕಲ್ ನಂ',
    namenumber: 'ಹೆಸರು ಸಂಖ್ಯೆ',
    evilnumber: 'ದುಷ್ಟ ಸಂಖ್ಯೆ',
    yourname: 'ನಿಮ್ಮ ಹೆಸರು',
    todayDate: 'ಇಂದು ದಿನಾಂಕ',
    raicalruler: 'ಆಮೂಲಾಗ್ರ ಆಡಳಿತಗಾರ',
    friendlynumber: 'ಸ್ನೇಹಪರ ಸಂಖ್ಯೆ',
    neutralday: 'ತಟಸ್ಥ ದಿನಗಳು',
    favorabledays: 'ಅನುಕೂಲಕರ ದಿನಗಳು',
    favourablestone: 'ಅನುಕೂಲಕರ ಕಲ್ಲು',
    favouabkesubstone: 'ಅನುಕೂಲಕರ ಉಪ ಕಲ್ಲು',
    favourableGod: 'ಅನುಕೂಲಕರ ದೇವರು',
    favourableMetal: 'ಅನುಕೂಲಕರ ಲೋಹ',
    favorableColor: 'ಅನುಕೂಲಕರ ಬಣ್ಣ',
    favourablemantra: 'ಅನುಕೂಲಕರ ಮಂತ್ರ',
    yourlifestone: 'ನಿಮ್ಮ ಲೈಫ್ ಸ್ಟೋನ್',
    yourbeneficstone: 'ನಿಮ್ಮ ಬೆನಿಫಿಕ್ ಸ್ಟೋನ್',
    yourluckystone: 'ನಿಮ್ಮ ಅದೃಷ್ಟದ ಕಲ್ಲು',
    subsitute: 'ಬದಲಿ',
    finger: 'ಬೆರಳು',
    weight: 'ತೂಕ',
    day: 'ದಿನ',
    diety: 'ಆಹಾರ ಪದ್ಧತಿ',
    metal: 'ಲೋಹದ',
    birthchart: 'ಜನ್ಮ ಚಾರ್ಟ್',
    chalitchart: 'ಚಲಿತ್ ಚಾರ್ಟ್',
    moonchart: 'ಚಂದ್ರನ ಚಾರ್ಟ್',
    sunchart: 'ಸೂರ್ಯ ಚಾರ್ಟ್',
    horachart: 'ಹೋರಾ ಚಾರ್ಟ್',
    dreskhanchart: 'ದ್ರೇಶ್ಕನ್ ಚಾರ್ಟ್',
    chaturchart: 'ಚತುರ್ಥಮಾಷಾ ಚಾರ್ಟ್',
    panchmanshachart: 'ಪಂಚಮಾಂಶ ಚಾರ್ಟ್',
    saptmanshachart: 'ಸಪ್ತಮಾನ ಚಾರ್ಟ್',
    asthamanshachart: 'ಅಷ್ಟಮಾನ ಚಾರ್ಟ್',
    navmanshachart: 'ನವಮಾನ ಚಾರ್ಟ್',
    dashmanshachart: 'ದಶಮಾನ ಚಾರ್ಟ್',
    dwadashachart: 'ದ್ವಾದಶ ಚಾರ್ಟ್',
    shodashamnshachart: 'ಷೋಡಶಾಂಶ ಚಾರ್ಟ್',
    vishmnashachart: 'ವಿಷಮಾಂಶ ಚಾರ್ಟ್',
    chaturmanshachat: 'ಚತುರ್ವಿಂಶಾಂಶ ಚಾರ್ಟ್',
    bhamshachart: 'ಭಮ್ಶಾ ಚಾರ್ಟ್',
    trishamanshachart: 'ತ್ರಿಶಮಾಂಶ ಚಾರ್ಟ್',
    khavedamshachart: 'ಖವೇದಾಂಶ ಚಾರ್ಟ್',
    akshvedanshachart: 'ಅಕ್ಷವೇದಾಂಶ ಚಾರ್ಟ್',
    shashtymshachart: 'ಷಷ್ಟಿಂಶ ಚಾರ್ಟ್',
    kalsarpd: 'ಕಲಸರ್ಪ ದೋಷ',
    mangalikd: 'ಮಾಂಗಲಿಕ್ ದೋಷ',
    sadesatidosha: 'ಸಾಧೇಸತಿ ದೋಷ',
    sdate: 'ದಿನಾಂಕ',
    moonsign: 'ಚಂದ್ರನ ಚಿಹ್ನೆ',
    saturnsign: 'ಶನಿಯ ರಾಶಿ',
    retro: 'ರೆಟ್ರೋ',
    type: 'ಮಾದರಿ',
    sldetail: 'ಸಾಧೇಶತಿ ಜೀವನ ವಿವರಗಳು',
    sign: 'ಸಹಿ ಮಾಡಿ',
    platnet: 'ಗ್ರಹಗಳು',
    horoscopechart: 'ನಿಮ್ಮ ಜಾತಕ ಚಾರ್ಟ್',
    hm: 'ಹಿಂದೂ ತಿಂಗಳು ಮತ್ತು ವರ್ಷ',
    vikram: 'ವಿಕ್ರಮ್ ಸಂವತ್',
    shaka: 'ಶಾಖಾ ಸಂವತ್',
    paksha: 'ಪಕ್ಷ',
    ayana: 'ಅಯನ',
    purnimanta: 'ಪೂರ್ಣಿಮಂತ',
    amanta: 'ಅಮಂತ',
    sumsign: 'ರಾಶಿ, ರಾಶಿ ಫಲ',
    panchangelement: 'ಪಂಚಾಂಗ ಅಂಶಗಳು',
    tithi: 'ತಿಥಿ',
    nakshtra: 'ನಕ್ಷತ್ರ',
    yog: 'ಯೋಗ',
    karan: 'ಕರಣ್',
    upto: 'ತನಕ',
    basicdetail: 'ಮೂಲ ವಿವರಗಳು',
    sunrise: 'ಸೂರ್ಯೋದಯ',
    sunset: 'ಸೂರ್ಯಾಸ್ತ',
    moonrise: 'ಚಂದ್ರನ ಉದಯ',
    moonset: 'ಚಂದ್ರನ ಸೆಟ್',
    hindusunrise: 'ಹಿಂದೂ ಸೂರ್ಯೋದಯ',
    hindusunset: 'ಹಿಂದೂ ಸೂರ್ಯಾಸ್ತ',
    changeDetail: 'ವಿವರಗಳನ್ನು ಬದಲಾಯಿಸಿ',
    panchangfor: 'ಪಂಚಂಗ್ ಫಾರ್',
    panchangDetail: 'ಪಂಚಾಂಗದ ವಿವರಗಳು',
    horamau: 'ಹೋರಾ ಮುಹೂರ್ತ',
    chaugidya: 'ಚೌಘಡಿಯ ಮುಹೂರ್ತ',
    daychaugidiya: 'ದಿನ ಚೋಘಡಿಯಾ',
    nightchau: 'ರಾತ್ರಿ ಚೌಘಡಿಯಾ',
    dayhora: 'ದಿನ ಹೋರಾ',
    nighthora: 'ರಾತ್ರಿ ಹೋರಾ',
    ritu: 'ರಿತು',
  },
  ta: {
    Availability: 'கிடைக்கும்',
    astrologerRegistration: 'Astrologer Registration',
    recharge: 'மீள்நிரப்பு',
    sendgift: 'பரிசு அனுப்பு',
    sendagift: 'ஒரு பரிசு அனுப்பு',
    gift: 'பரிசுகள்',
    notification: 'அறிவிப்புகள்',
    about: 'பற்றி',
    skip: 'தவிர்க்கவும்',
    mobile: 'கைபேசி',
    wewill: 'உங்கள் தொலைபேசி எண்ணுக்கு ஒரு முறை குறியீட்டை அனுப்புவோம்',
    agree: 'நீங்கள் ஆஸ்ட்ரோஜோதிஷுக்கு ஒப்புக்கொள்கிறீர்கள்',
    terms: 'விதிமுறைகள் மற்றும் நிபந்தனைகள்',
    and: 'மற்றும்',
    privacy: 'தனியுரிமைக் கொள்கை',
    getotp: 'OTP பெறவும்',
    connect: 'அல்லது இணைக்கவும்',
    facebook: 'Facebook மூலம் பதிவு செய்யவும்',
    google: 'Google உடன் பதிவு செய்யவும்',
    enter: 'மொபைல் எண்ணை உள்ளிடவும்',
    pleaseenter: 'மொபைல் எண்ணை உள்ளிடவும்',
    accepttc:
      'எங்கள் விதிமுறைகள் மற்றும் நிபந்தனைகள் மற்றும் தனியுரிமைக் கொள்கையை ஏற்கவும்',
    verification: 'சரிபார்ப்பு',
    smsotp: 'எஸ்எம்எஸ் மூலம் OTP கிடைக்கும்',
    verify: 'சரிபார்க்கவும்',
    didnt: 'சரிபார்ப்பு OTP பெறவில்லையா?',
    resendagain: 'மீண்டும் அனுப்பவும்',
    pleaseenterver: 'சரிபார்ப்புக் குறியீட்டை உள்ளிடவும்',
    verificationsendonmobile:
      'உங்கள் மொபைலில் சரிபார்ப்புக் குறியீடு அனுப்பப்பட்டுள்ளது.',
    userregistration: 'உபயோகிப்போர் பதிவு',
    name: 'பெயர்',
    mailid: 'அஞ்சல் ஐடி',
    gender: 'பாலினம்',
    male: 'ஆண்',
    female: 'பெண்',
    others: 'மற்றவைகள்',
    dob: 'பிறந்த தேதி',
    tob: 'பிறந்த நேரம்',
    pob: 'பிறந்த இடம்',
    address: 'முகவரி',
    marital: 'திருமண நிலை',
    enterpartnerdetail: 'கூட்டாளியின் விவரங்களை உள்ளிடவும்',
    pname: 'கூட்டாளியின் பெயர்',
    pdob: 'கூட்டாளியின் பிறந்த தேதி',
    ptob: 'கூட்டாளியின் பிறந்த நேரம்',
    ppob: 'கூட்டாளியின் பிறந்த இடம்',
    create: 'உருவாக்கு',
    mywallet: 'என் பணப்பை',
    walletbalance: 'பணப்பை இருப்பு',
    consultationhistory: 'ஆலோசனை வரலாறு',
    choosea: 'கிடைக்கும் ரீசார்ஜ் பேக்குகளில் இருந்து தேர்வு செய்யவும்',
    extra: 'கூடுதல்',
    rechargepack:
      'உங்கள் ரீசார்ஜ் பேக் பல ஜோதிடர்களுக்குப் பயன்படுத்தப்படலாம்.',
    proceed: 'பணம் செலுத்த தொடரவும்',
    pleaseselectamount: 'ரீசார்ஜ் செய்வதற்கான தொகையைத் தேர்ந்தெடுக்கவும்',
    paymentdetail: 'கட்டண விவரங்கள்',
    totalamount: 'மொத்த தொகை',
    gst: 'ஜிஎஸ்டி',
    totalpayable: 'செலுத்த வேண்டிய மொத்த தொகை',
    couponcode: 'கூப்பன் குறியீடு',
    apply: 'விண்ணப்பிக்கவும்',
    recommended: 'பரிந்துரைக்கப்பட்ட முறைகள்',
    paymentmethod: 'பணம் செலுத்தும் முறைகள்',
    bonus: 'போனஸ்',
    onr: 'ரீசார்ஜ் தொகையில்',
    balanceafter: 'ரீசார்ஜ் செய்த பிறகு உங்கள் பணப்பையில் இருப்பு வைக்கவும்',
    paytm: 'Paytm',
    upi: 'UPI',
    rupay: 'ரூபாய்',
    debitcard: 'டெபிட் கார்டு',
    creditcard: 'கடன் அட்டை',
    paypal: 'பேபால்',
    netbanking: 'நெட் பேங்கிங்',
    cred: 'கடன்',
    freecharge: 'இலவச கட்டணம்',
    walletTransaction: 'வாலட் பரிவர்த்தனை',
    confirmation: 'உறுதிப்படுத்தல்',
    rechargesucessfully: 'ரீசார்ஜ் வெற்றி',
    continue: 'தொடரவும்',
    search: 'தேடு',
    chat: 'அரட்டை',
    call: 'அழைப்பு',
    video: 'காணொளி',
    booking: 'பதிவு',
    astrologer: 'ஜோதிடரின்',
    onlinepuja: 'ஆன்லைன் பூஜை',
    blog: 'வலைப்பதிவு',
    astrovideos: 'ஆஸ்ட்ரோஜோதிஷ் வீடியோக்கள்',
    astronews: 'செய்திகளில் ஆஸ்ட்ரோஜோதிஷ்',
    freeservice: 'இலவச சேவைகள்',
    shareyourfeedback:
      'பயன்பாட்டை மேம்படுத்த எங்களுக்கு உதவ உங்கள் கருத்தைப் பகிரவும்',
    typereview: 'உங்கள் மதிப்பாய்வை உள்ளிடவும்...',
    submit: 'சமர்ப்பிக்கவும்',
    private: 'தனிப்பட்ட மற்றும் ரகசியமானது',
    verified: 'சரிபார்க்கப்பட்ட ஜோதிடர்கள்',
    secure: 'பாதுகாப்பான கட்டணம்',
    kundali: 'குண்டலி',
    matchmaking: 'மேட்ச் மேக்கிங்',
    festival: 'திருவிழாக்கள்',
    panchang: 'பஞ்சாங்கம்',
    applanguage: 'உங்கள் பயன்பாட்டு மொழியைத் தேர்ந்தெடுக்கவும்',
    english: 'ஆங்கிலம்',
    tamil: 'தமிழ்',
    hindi: 'ஹிந்தி',
    kannada: 'கன்னடம்',
    telegu: 'தெலுங்கு',
    bangla: 'பங்களா',
    reviews: 'விமர்சனங்கள்',
    puja: 'உங்கள் தேவைகள் மற்றும் தேவைகளைப் பொறுத்து அனைத்து வகையான பூஜை சேவைகளையும் வழங்க ஆன்லைன் பூஜை அர்ப்பணிக்கப்பட்டுள்ளது. உங்கள் தேதி மற்றும் நேரத்தை முன்பதிவு செய்த பிறகு, பூஜைப் பொருட்கள் வாங்குவதற்கான வழிமுறைகள் (எ.கா. சர்க்கரை, சிறிய சிலை, பால் போன்றவை) அத்துடன் சில எளிய வழிமுறைகளையும் (எ.கா. சுத்தமான உணவு, மது அருந்தக்கூடாது) நீங்கள் அதிகமாகப் பெறுவீர்கள். பூஜையின் போது பரவும் நம்பமுடியாத குணப்படுத்தும் ஆற்றல்.',
    astrologerDetail: 'ஜோதிடர் விவரங்கள்',
    readmore: 'மேலும் படிக்க',
    showless: 'குறைவாகக் காட்டு',
    year: 'ஆண்டு',
    chatwith: 'ஜோதிடருடன் அரட்டையடிக்கவும்',
    talkwith: 'ஜோதிடரிடம் பேசுங்கள்',
    videowith: 'ஜோதிடருடன் வீடியோ அழைப்பு',
    astrologers: 'ஜோதிடர்கள்',
    myaccount: 'என் கணக்கு',
    profile: 'சுயவிவரம்',
    customerSupport: 'வாடிக்கையாளர் ஆதரவு',
    edit: 'தொகு',
    share: 'பகிர்',
    consulationsummary: 'ஆலோசனை சுருக்கம்',
    logout: 'வெளியேறு',
    paymenthistory: 'கட்டண வரலாறு',
    orderhistory: 'ஆர்டர் வரலாறு',
    getReport: 'அறிக்கையைப் பெறுங்கள்',
    enterreferalcode: 'பரிந்துரை குறியீட்டை உள்ளிடவும்',
    status: 'நிலை',
    callrate: 'அழைப்பு விகிதம்',
    duration: 'கால அளவு',
    deduction: 'Deduction',
    createprofile: 'சுயவிவரத்தை உருவாக்கவும்',
    update: 'புதுப்பிக்கவும்',
    show: 'காட்டு',
    resetall: 'அனைத்தையும் மீட்டமைக்கவும்',
    boydetail: 'பையன் விவரம்',
    girldetail: 'பெண்ணின் விவரம்',
    matchoroscope: 'பொருத்த ஜாதகம்',
    isrequired: 'தேவை',
    compatibilty: 'பொருந்தக்கூடிய மதிப்பெண்',
    conclusion: 'ஆஸ்ட்ரோஜோதிஷ் முடிவு',
    getKundali: 'குண்டலியைக் காண்க',
    sharemy: 'எனது போட்டியைப் பகிரவும்',
    consultwith: 'ஜோதிடரிடம் ஆலோசிக்கவும்',
    yourastrodetail: 'உங்கள் ஆஸ்ட்ரோ விவரங்கள்',
    kundalichart: 'குண்டலி விளக்கப்படங்கள்',
    doshareports: 'தோஷா அறிக்கைகள்',
    remedies: 'பரிகாரங்கள்',
    numerlogyreport: 'எண் கணித அறிக்கைகள்',
    destinityno: 'விதி எண்',
    radicalno: 'தீவிர எண்',
    namenumber: 'பெயர் எண்',
    evilnumber: 'தீய எண்',
    yourname: 'உங்கள் பெயர்',
    todayDate: 'இன்று தேதி',
    raicalruler: 'தீவிர ஆட்சியாளர்',
    friendlynumber: 'நட்பு எண்',
    neutralday: 'நடுநிலை நாட்கள்',
    favorabledays: 'சாதகமான நாட்கள்',
    favourablestone: 'சாதகமான கல்',
    favouabkesubstone: 'சாதகமான துணை கல்',
    favourableGod: 'அனுகூலமான கடவுள்',
    favourableMetal: 'சாதகமான உலோகம்',
    favorableColor: 'சாதகமான நிறம்',
    favourablemantra: 'சாதகமான மந்திரம்',
    yourlifestone: 'உங்கள் வாழ்க்கை கல்',
    yourbeneficstone: 'உங்கள் நன்மை கல்',
    yourluckystone: 'உங்கள் அதிர்ஷ்ட கல்',
    subsitute: 'மாற்று',
    finger: 'விரல்',
    weight: 'எடை',
    day: 'நாள்',
    diety: 'உணவுமுறை',
    metal: 'உலோகம்',
    birthchart: 'பிறப்பு விளக்கப்படம்',
    chalitchart: 'சலித் விளக்கப்படம்',
    moonchart: 'சந்திரன் விளக்கப்படம்',
    sunchart: 'சூரிய விளக்கப்படம்',
    horachart: 'ஹோரா விளக்கப்படம்',
    dreskhanchart: 'ட்ரெஷ்கன் விளக்கப்படம்',
    chaturchart: 'சதுர்தமாஷ விளக்கப்படம்',
    panchmanshachart: 'பஞ்சமன்ஷா விளக்கப்படம்',
    saptmanshachart: 'சப்தமான்ஷா விளக்கப்படம்',
    asthamanshachart: 'அஷ்டமான்ஷா விளக்கப்படம்',
    navmanshachart: 'நவமான்ஷா விளக்கப்படம்',
    dashmanshachart: 'தசாமான்ஷா விளக்கப்படம்',
    dwadashachart: 'துவாதச விளக்கப்படம்',
    shodashamnshachart: 'ஷோடசம்ஷா விளக்கப்படம்',
    vishmnashachart: 'விஷமன்ஷா விளக்கப்படம்',
    chaturmanshachat: 'சதுர்விம்ஷா விளக்கப்படம்',
    bhamshachart: 'பாம்ஷா விளக்கப்படம்',
    trishamanshachart: 'த்ரிஷாமான்ஷா விளக்கப்படம்',
    khavedamshachart: 'கவேதம்ஷா விளக்கப்படம்',
    akshvedanshachart: 'அக்ஷ்வேதன்ஷா விளக்கப்படம்',
    shashtymshachart: 'ஷஷ்டிம்ஷா விளக்கப்படம்',
    kalsarpd: 'காலசர்ப்ப தோஷம்',
    mangalikd: 'மாங்கலிக் தோசை',
    sadesatidosha: 'சதேசதி தோஷம்',
    sdate: 'தேதி',
    moonsign: 'சந்திரன் அடையாளம்',
    saturnsign: 'சனி ராசி',
    retro: 'ரெட்ரோ',
    type: 'வகை',
    sldetail: 'சதேசதி வாழ்க்கை விவரங்கள்',
    sign: 'கையெழுத்து',
    platnet: 'கிரகங்கள்',
    horoscopechart: 'உங்கள் ஜாதக விளக்கப்படம்',
    hm: 'இந்து மாதம் & ஆண்டு',
    vikram: 'விக்ரம் சம்வத்',
    shaka: 'ஷாகா சம்வத்',
    paksha: 'பக்ஷா',
    ayana: 'அயனா',
    purnimanta: 'பூர்ணிமந்தா',
    amanta: 'அமந்தா',
    sumsign: 'சூரியன் அடையாளம்',
    panchangelement: 'பஞ்சாங்க கூறுகள்',
    tithi: 'திதி',
    nakshtra: 'நக்ஷத்ரா',
    yog: 'யோகம்',
    karan: 'கரன்',
    upto: 'அது வரை',
    basicdetail: 'அடிப்படை விவரங்கள்',
    sunrise: 'சூரிய உதயம்',
    sunset: 'சூரிய அஸ்தமனம்',
    moonrise: 'சந்திர உதயம்',
    moonset: 'சந்திரன் அமைவு',
    hindusunrise: 'இந்து சூரிய உதயம்',
    hindusunset: 'இந்து சூரிய அஸ்தமனம்',
    changeDetail: 'விவரங்களை மாற்றவும்',
    panchangfor: 'பஞ்சாங் ஃபார்',
    panchangDetail: 'பஞ்சாங்க விவரங்கள்',
    horamau: 'ஹோரா முஹூர்த்தம்',
    chaugidya: 'சௌகாதியா முஹூர்த்தா',
    daychaugidiya: 'டேய் சோகடியா',
    nightchau: 'இரவு சௌகாதியா',
    dayhora: 'நாள் ஹோரா',
    nighthora: 'இரவு ஹோரா',
    ritu: 'ரிது',
  },
});

export default stringsoflanguages;
