import {Dimensions, StyleSheet} from 'react-native';

const fontFamilys = {
  roman: 'AvenirLTStd-Roman',
  medium: 'AvenirLTStd-Medium',
  heavy: 'AvenirLTStd-heavy',
};

const colorcode = {
  black: '#204768',
  lightyellow: '#EDB20E17',
  yellow: '#FFC613',
  facebookcolor: '#2773CB',
  white: 'white',
  googlecolor: '#FC3750',
  dblack: '#0B0D3960',
  ddblack: '#0B0D39',
  grey: '#717171',
  yellowbackground: '#FFD23A80',
  blackc: 'black',
  lightgrey: '#B9B9B9',
  headeryellow: '#FFC613',
  offwhite: 'FFFFFF59',
  headeryellow33: '#FFC61361',
};

const dimensions = {
  width: Dimensions.get('window').width,
  height: Dimensions.get('window').height,
};

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  skip: {
    fontFamily: fontFamilys.roman,
    fontSize: 15,
    color: colorcode.black,
    alignSelf: 'flex-end',
    margin: 20,
  },
  consulation: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    margin: 10,
    height: 50,
  },
  middlebanner: {
    width: dimensions.width - 20,
    height: 70,
    resizeMode: 'stretch',
  },

  loginlogo: {
    width: dimensions.width - 150,
    alignSelf: 'center',
    height: 200,
    resizeMode: 'contain',
    marginTop: 22,
  },
  facebookimage: {
    width: 40,
    height: 25,
    margin: 8,
    resizeMode: 'contain',
  },
  facebookimage1: {
    width: 25,
    height: 25,
    margin: 8,
    resizeMode: 'contain',
  },
  aimage: {
    width: 18,
    height: 18,
    resizeMode: 'contain',
    marginTop: 4,
  },
  arrowimage: {
    width: 20,
    height: 20,
    margin: 8,
    marginTop: 12,
    resizeMode: 'contain',
  },
  giftimage: {
    width: 40,
    height: 40,
    margin: 8,
    resizeMode: 'contain',
    marginTop: 20,
  },
  payimage: {
    width: 47,
    height: 20,
    margin: 8,
    resizeMode: 'contain',
    marginTop: 14,
    alignSelf: 'center',
  },
  languagepoptext: {
    fontFamily: fontFamilys.medium,
    color: colorcode.black,
    fontSize: 20,
    textAlign: 'center',
  },
  pujaImage: {width: 120, height: 120, resizeMode: 'contain'},
  pujaText: {
    width: 200,
    fontSize: 10,
    marginLeft: 6,
    marginTop: 8,
    lineHeight: 10,
    fontFamily: '#2a2a2a',
  },
  payview: {
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
    backgroundColor: 'white',
    width: dimensions.width / 3.7,
    height: 67,
    margin: 10,
  },
  pujaview: {
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
    backgroundColor: 'white',
    width: dimensions.width - 20,
    height: 120,
    margin: 10,
    borderRadius: 8,
    flexDirection: 'row',
    marginTop: -12,
  },
  gifttext: {
    color: colorcode.black,
    fontFamily: fontFamilys.roman,
    fontSize: 15,
    marginTop: 22,
    width: dimensions.width - 70,
  },
  checkimage: {
    width: 20,
    height: 20,
    marginTop: 8,
    resizeMode: 'contain',
  },
  agree: {
    color: colorcode.black,
    fontFamily: fontFamilys.roman,
    fontSize: 11,
    marginLeft: '5%',
    marginTop: 8,
    width: '90%',
    textAlign: 'center',
    lineHeight: 17,
  },
  partnerDetail: {
    color: colorcode.black,
    fontFamily: fontFamilys.medium,
    fontSize: 15,
    lineHeight: 17,
    marginLeft: 48,
    marginTop: 12,
  },
  girlDetail: {
    color: colorcode.black,
    fontFamily: fontFamilys.medium,
    fontSize: 15,
    lineHeight: 17,
    marginTop: 12,
    textAlign: 'center',
  },
  blogText: {
    color: colorcode.black,
    fontFamily: fontFamilys.medium,
    fontSize: 17,
    lineHeight: 17,
    margin: 10,
  },
  accountrow: {flexDirection: 'row'},
  accountrow1: {flexDirection: 'row', width: dimensions.width / 2},
  searchicon: {width: 20, height: 20, margin: 9, resizeMode: 'contain'},
  homemenu: {
    width: 20,
    height: 20,
    margin: 12,
    marginTop: 25,
    resizeMode: 'contain',
  },
  homemenuicon: {
    width: 20,
    height: 20,
    margin: 4,
    marginTop: 25,
    resizeMode: 'contain',
  },
  homewallet: {
    color: 'white',
    fontFamily: fontFamilys.roman,
    fontSize: 16,
    marginRight: 9,
    marginLeft: 3,
    marginTop: 25,
  },
  searchtext: {
    color: 'white',
    fontFamily: fontFamilys.roman,
    fontSize: 16,
    marginRight: 9,
    marginLeft: 3,
    marginTop: 10,
  },
  headerview: {
    height: 65,
    backgroundColor: '#FFC613',
    flexDirection: 'row',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
    width: dimensions.width,
  },
  blogdetailView: {height: 160, width: dimensions.width},
  astrologerDetailView: {
    height: 150,
    width: dimensions.width,
    margin: 5,
    borderRadius: 3,
    backgroundColor: colorcode.white,
  },
  astrologerView: {
    height: 140,
    width: dimensions.width / 2 - 10,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 7,
    margin: 5,
    borderRadius: 3,
    backgroundColor: colorcode.white,
  },
  consultationView: {
    width: dimensions.width - 20,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 7,
    margin: 5,
    borderRadius: 3,
    backgroundColor: colorcode.white,
  },
  htmldetailView: {
    width: dimensions.width - 20,
    alignSelf: 'center',
  },
  headerInput: {
    backgroundColor: '#ffffff49',
    height: 38,
    width: dimensions.width / 2,
    borderRadius: 22,
    marginTop: 15,
    flexDirection: 'row',
  },
  underlineStyleBase: {
    width: 70,
    height: 45,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#00000010',
    color: colorcode.black,
  },
  giftview: {
    backgroundColor: colorcode.yellowbackground,
    height: 90,
    borderRadius: 4,
    flexDirection: 'row',
    marginTop: 12,
    width: dimensions.width - 20,
    alignSelf: 'center',
  },
  terms: {
    color: colorcode.black,
    fontFamily: fontFamilys.roman,
    fontSize: 11,
    fontWeight: 'bold',
    textDecorationLine: 'underline',
  },
  facebooktext: {
    color: colorcode.white,
    fontSize: 15,
    fontFamily: fontFamilys.medium,
    margin: 10,
  },
  radiostyle: {fontFamily: 'AvenirLTStd-Medium', fontSize: 12, marginRight: 12},
  loginmobile: {
    fontFamily: fontFamilys.medium,
    fontSize: 17,
    color: colorcode.black,
    marginTop: -35,
    textAlign: 'center',
  },
  wewill: {
    fontFamily: fontFamilys.roman,
    fontSize: 12,
    color: colorcode.black,
    textAlign: 'center',
    margin: 20,
    width: '70%',
    alignSelf: 'center',
  },
  accountWill: {
    fontFamily: fontFamilys.medium,
    fontSize: 12,
    color: colorcode.black,
    marginLeft: 0,
    marginTop: 12,
  },
  profileWill: {
    fontFamily: fontFamilys.roman,
    fontSize: 13,
    color: '#0B0D39',
    marginLeft: 0,
    marginTop: 12,
  },
  formstyle: {marginTop: 8, marginLeft: 12},
  row: {
    flexDirection: 'row',
    marginTop: 6,
    width: dimensions.width - 80,
    alignSelf: 'center',
  },

  srow: {
    flexDirection: 'row',
    marginTop: 22,
    width: dimensions.width - 60,
    alignSelf: 'center',
  },
  srow1: {
    flexDirection: 'row',
    marginTop: 10,
    width: dimensions.width - 60,
    alignSelf: 'center',
  },
  grow1: {
    marginTop: 10,
    width: dimensions.width - 60,
    alignSelf: 'center',
  },
  facebookrow: {
    flexDirection: 'row',
    marginTop: 16,
    width: dimensions.width - 80,
    alignSelf: 'center',
    backgroundColor: colorcode.facebookcolor,
    height: 40,
    borderRadius: 6,
  },
  googlerow: {
    flexDirection: 'row',
    marginTop: 16,
    width: dimensions.width - 80,
    alignSelf: 'center',
    backgroundColor: colorcode.googlecolor,
    height: 40,
    borderRadius: 6,
  },

  coupondata: {
    fontFamily: fontFamilys.medium,
    fontSize: 10,
    margin: 2,
    textAlign: 'right',
  },
  code: {
    width: 60,
    borderRadius: 8,
    height: 45,
    backgroundColor: colorcode.lightyellow,
  },
  signupcode: {
    width: 60,
    borderRadius: 8,
    height: 45,
    borderColor: colorcode.yellow,
    borderWidth: 1,
  },
  chartimage: {
    width: 300,
    height: 200,
    alignSelf: 'center',
    resizeMode: 'contain',
  },
  signupmobile: {
    width: dimensions.width - 80,
    borderRadius: 8,
    height: 45,
    borderColor: colorcode.yellow,
    borderWidth: 0,
    marginLeft: 10,
    backgroundColor: '#f1f1f1',
  },
  mobile: {
    width: dimensions.width - 150,
    borderRadius: 8,
    height: 45,
    backgroundColor: colorcode.lightyellow,
    marginLeft: 10,
  },
  mobile1: {
    width: dimensions.width - 20,
    borderRadius: 8,
    height: 45,
    backgroundColor: colorcode.lightyellow,
    marginLeft: 10,
  },
  countrypicker: {
    width: 40,
    height: 40,
    marginLeft: 12,
    marginTop: 5,
    color: colorcode.black,
  },
  input: {
    width: dimensions.width - 150,
    height: 45,
    marginLeft: 1,
    color: colorcode.black,
    fontFamily: fontFamilys.medium,
  },
  input23: {
    width: dimensions.width - 20,
    height: 45,
    marginLeft: 1,
    color: colorcode.black,
    fontFamily: fontFamilys.medium,
  },
  applyview: {
    backgroundColor: colorcode.yellow,
    width: 100,
    height: 48,
    marginLeft: 27,
  },
  connect: {
    textAlign: 'center',
    fontFamily: fontFamilys.roman,
    fontSize: 15,
    marginTop: 9,
  },
  match: {
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
    width: dimensions.width - 20,
    margin: 10,
    height: 200,
    backgroundColor: 'white',
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderRadius: 12,
  },
  didnt: {
    color: '#A6A7A9',
    fontFamily: 'AvenirLTStd-Medium',
    fontSize: 18,
    marginTop: 30,
    textAlign: 'center',
  },
  resend: {
    color: colorcode.yellow,
    fontFamily: fontFamilys.medium,
    fontSize: 17,
    textAlign: 'center',
    textDecorationLine: 'underline',
    textDecorationStyle: 'solid',
    textDecorationColor: '#000',
    marginTop: 12,
  },

  button: {
    width: dimensions.width - 80,
    height: 45,
    alignSelf: 'center',
    marginTop: 20,
  },
  lbutton: {
    width: 100,
    height: 45,
    alignSelf: 'center',
    marginTop: 20,
  },
  walletamount: {
    fontFamily: fontFamilys.medium,
    fontSize: 16,
    marginTop: 3,
    textAlign: 'center',
    color: colorcode.dblack,
  },
  walletbalance: {
    fontFamily: fontFamilys.medium,
    fontSize: 37,
    margin: 10,
    color: colorcode.dblack,
  },
  walletbalance1: {
    fontFamily: fontFamilys.medium,
    fontSize: 20,
    margin: 10,
    color: colorcode.black,
  },
  walletview: {
    width: dimensions.width,
    borderBottomColor: '#EDEDED',
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  credit: {
    fontFamily: fontFamilys.medium,
    fontSize: 15,
    margin: 5,
    marginRight: 80,
    marginTop: 14,
    color: '#2AC17E',
  },
  txn: {
    fontFamily: fontFamilys.medium,
    fontSize: 15,
    margin: 5,
    marginLeft: 1,
    marginTop: 14,
    color: '#333333',
  },
  rechargesucc: {
    marginTop: 10,
    fontSize: 25,
    color: colorcode.black,
    fontFamily: fontFamilys.medium,
    textAlign: 'center',
  },
  checkedstyle: {
    width: 112,
    height: 112,
    marginTop: 100,
    marginLeft: 0,
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  walletimageview: {
    backgroundColor: colorcode.yellow,
    width: 40,
    height: 40,
    borderRadius: 20,
    margin: 10,
  },
  created: {
    fontFamily: fontFamilys.medium,
    fontSize: 12,
    margin: 5,
    color: '#00000040',
    marginTop: 1,
  },
  debit: {
    fontFamily: fontFamilys.medium,
    fontSize: 15,
    margin: 5,
    marginRight: 80,
    marginTop: 14,
    color: '#FF001F',
  },
  youtube: {
    position: 'absolute',
    top: 30,
    width: 30,
    height: 30,
    alignSelf: 'center',
  },
  astrologerrow: {flexDirection: 'row'},
  onlineView: {
    height: 8,
    width: 8,
    borderRadius: 4,
    position: 'absolute',
    top: 3,
    right: 4,
  },
  editView: {
    fontFamily: fontFamilys.medium,
    marginRight: 12,
    color: colorcode.yellow,
    fontSize: 18,
  },
  editText: {
    fontFamily: fontFamilys.medium,
    marginRight: 12,
    color: colorcode.ddblack,
    fontSize: 28,
    textAlign: 'center',
  },
  onlineView1: {
    height: 8,
    width: 8,
    borderRadius: 4,
    top: 3,
    right: 4,
  },

  dt_name: {
    fontFamily: fontFamilys.medium,
    fontSize: 12,
    marginTop: 12,
    marginLeft: -6,
    color: colorcode.ddblack,
    width: dimensions.width / 2 - 80,
  },
  qdt_name: {
    fontFamily: fontFamilys.medium,
    fontSize: 16,
    marginTop: 12,
    marginLeft: -6,
    color: colorcode.ddblack,
  },
  dt_speciality: {
    fontFamily: fontFamilys.roman,
    fontSize: 11,
    marginTop: 12,
    marginLeft: -6,
    color: colorcode.ddblack,
    width: dimensions.width / 2 - 80,
  },
  qdt_speciality: {
    fontFamily: fontFamilys.roman,
    fontSize: 12,
    marginTop: 12,
    marginLeft: -6,
    color: colorcode.ddblack,
  },
  dt_specialityq: {
    fontFamily: fontFamilys.roman,
    fontSize: 11,
    marginTop: 12,
    marginLeft: -6,
    color: colorcode.ddblack,
  },
  astrologerImage: {width: 52, height: 52, borderRadius: 26, margin: 12},
  astrologerDetailImage: {width: 70, height: 70, borderRadius: 35, margin: 12},
  ex_starView: {flexDirection: 'row', marginTop: 2, marginLeft: 9},
  ex_starImage: {width: 12, height: 12, resizeMode: 'contain'},
  couponcodeview: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: colorcode.yellow,
    height: 50,
    borderRadius: 5,
    width: dimensions.width - 20,
    alignSelf: 'center',
    marginTop: 12,
  },
  paymentside: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: -5,
    width: '100%',
  },
  blogside: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: dimensions.width,
  },
  languagecheck: {width: 22, height: 22, resizeMode: 'contain', marginTop: 8},
  languagetext: {
    fontFamily: fontFamilys.medium,
    fontSize: 14,
    margin: 12,
    color: colorcode.white,
    width: dimensions.width / 4.6,
  },
  newstext: {
    fontFamily: fontFamilys.medium,
    fontSize: 14,
    margin: 4,
    color: colorcode.blackc,
  },
  authortext: {
    fontFamily: fontFamilys.medium,
    fontSize: 9,
    margin: 4,
    color: colorcode.lightgrey,
    width: '50%',
  },
  blogtext: {
    fontFamily: fontFamilys.medium,
    fontSize: 12,
    margin: 10,
    color: colorcode.lightgrey,
    marginTop: 1,
  },
  paymentsidetext: {
    fontFamily: fontFamilys.roman,
    fontSize: 14,
    margin: 12,
    marginTop: 4,
    color: colorcode.grey,
  },
  paymentrightside: {
    fontFamily: fontFamilys.medium,
    fontSize: 14,
    margin: 12,
    marginTop: 4,
    color: colorcode.grey,
    textAlign: 'left',
  },
  paymentdetail: {
    color: colorcode.black,
    fontFamily: fontFamilys.heavy,
    fontWeight: '700',
    fontSize: 17,
    margin: 12,
  },
  choose: {
    fontFamily: fontFamilys.medium,
    fontSize: 16,
    marginLeft: 16,
    marginTop: 2,
    color: colorcode.dblack,
  },
  consultationhistory: {
    fontFamily: fontFamilys.medium,
    fontSize: 20,
    margin: 10,
    marginTop: 3,
    color: colorcode.ddblack,
  },
  walletflatlist: {
    marginTop: 10,
    marginLeft: 5,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  freeflatlist: {
    marginTop: 10,
    marginLeft: 5,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  rechargestyle: {
    marginTop: 5,
    width: dimensions.width / 5,

    margin: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E2D5',
    marginLeft: 4,
  },
  dropdown1BtnStyle: {
    width: '100%',
    height: 50,
    borderColor: '#FFC613',
    backgroundColor: 'white',
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 12,
  },
  dropdown1BtnTxtStyle: {
    color: 'black',
    textAlign: 'left',
    fontSize: 14,

    fontFamily: fontFamilys.medium,
  },
  dropdown1DropdownStyle: {backgroundColor: '#EFEFEF'},
  dropdown1RowStyle: {backgroundColor: '#EFEFEF', borderBottomColor: '#C5C5C5'},
  dropdown1RowTxtStyle: {color: '#444', textAlign: 'left'},

  dropdown2BtnStyle: {
    width: '80%',
    height: 50,
    backgroundColor: '#444',
    borderRadius: 8,
  },
  dropdown2BtnTxtStyle: {
    color: '#FFF',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  dropdown2DropdownStyle: {
    backgroundColor: '#444',
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
  },
  dropdown2RowStyle: {backgroundColor: '#444', borderBottomColor: '#C5C5C5'},
  dropdown2RowTxtStyle: {
    color: '#FFF',
    textAlign: 'center',
    fontWeight: 'bold',
  },

  dropdown3BtnStyle: {
    width: '100%',
    height: 50,
    backgroundColor: '#FFF',
    paddingHorizontal: 0,
    borderWidth: 4,
    borderRadius: 8,
    borderColor: '#444',
  },
  dropdown3BtnChildStyle: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 18,
  },
  dropdown3BtnImage: {width: 45, height: 45, resizeMode: 'cover'},
  dropdown3BtnTxt: {
    color: '#444',
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 24,
    marginHorizontal: 12,
  },
  dropdown3DropdownStyle: {backgroundColor: 'slategray'},
  dropdown3RowStyle: {
    backgroundColor: 'slategray',
    borderBottomColor: '#444',
    height: 50,
  },
  dropdown3RowChildStyle: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: 18,
  },
  dropdownRowImage: {width: 45, height: 45, resizeMode: 'cover'},
  dropdown3RowTxt: {
    color: '#F1F1F1',
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 24,
    marginHorizontal: 12,
  },

  dropdown4BtnStyle: {
    width: '50%',
    height: 50,
    backgroundColor: '#FFF',
    borderRadius: 8,
    borderWidth: 4,
    borderColor: '#444',
  },
  dropdown4BtnTxtStyle: {color: '#444', textAlign: 'left'},
  dropdown4DropdownStyle: {backgroundColor: '#EFEFEF'},
  dropdown4RowStyle: {backgroundColor: '#EFEFEF', borderBottomColor: '#C5C5C5'},
  dropdown4RowTxtStyle: {color: '#444', textAlign: 'left'},
});
